### ISSUE TITLE
Storage connection string.

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-event-hubs-dotnet#102]
## Actual Behaviour
1. You ask for storage connection string. 

## Expected Behaviour
1. I expect to ask for the storage name and the storage key or SAS token instead.

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
Thanks for recommendation. We will consider this in our next client release.

**Comment by jtaubensee** [comment]
@Nepomuceno - Sorry for the delay. Doing a little clean up here.

I don't think it makes sense for the added complexity, considering you can get the storage account connection string from the portal. I do remember a time when this wasn't available, so maybe that was the case when you created this issue.

![2017-04-27_15h56_27](https://cloud.githubusercontent.com/assets/8162917/25507650/2f975630-2b62-11e7-9535-54ffee6e6d3c.png)
