### ISSUE TITLE
Cannot use EventProcessorHost with IoT Hub - $management did not match

### ISSUE THREAD

**Issue by parad0xchild** [Azure/azure-event-hubs-dotnet#103]
When trying to connect to IoT Hub using EventProcessorHost, it fails and returns this exception:

Encountered error while fetching the list of EventHub PartitionIds ---> Microsoft.Azure.Amqp.AmqpException: The link address '$management' did not match any of the expected formats.

Code works with Event Hub, but not with IoT Hub.

## Versions  
- OS platform and version: Visual Studio 2015
- .NET Version: .net core 1.0.0-preview2-003156
- NuGet package version or commit ID: 0.0.4-preview

**Comment by serkantkaraca** [comment]
.NetCore client doesn't support IOT URLs yet. You need to obtain Event Hub URL from Azure portal and start your receivers with that. Let me know if you have any questions.

**Comment by parad0xchild** [comment]
The issue has when using the event hub compatible endpoint url.

**Comment by serkantkaraca** [comment]
My first answer still applies. The URL or connection string you are using isn't Event Hubs. Can you paste the URL after removing identifiers?

**Comment by parad0xchild** [comment]
When using IoT Hub - this fails: 
`Endpoint=sb://<iothub>.azure-devices.net;SharedAccessKeyName=<name>;SharedAccessKey=<key>`

When using Event Hub this succeeds:
`Endpoint=sb://<eventhub>.servicebus.windows.net/;SharedAccessKeyName=<name>;SharedAccessKey=<key>";`

**Comment by serkantkaraca** [comment]
Good to hear you are unblocked. In the future, we will probably support IOT endpoints as well. This will avoid some hassle.

**Comment by sorenhoyer** [comment]
@serkantkaraca any chance of adding IOT endpoint support soon? Could we please reopen this?

**Comment by serkantkaraca** [comment]
IOT endpoint support is one of the top items in our client improvement plans. No need to to reopen the issue, we are already tracking it, no worries.

**Comment by sorenhoyer** [comment]
Thanks for the quick response. Looking forward to it!

**Comment by VikSab** [comment]
Any update on this issue - 

We are unable to receive events from IotHub endpoint using the EventHubProcessor .

**Comment by goncalo-oliveira** [comment]
I can't seem to be able to register to an IoT hub, even using the Event Hub-compatible endpoint. I get an exception saying that "The messaging entity 'sb://iothub-<thing>.servicebus.windows.net/messages/events' could not be found.".

Is the hub path affected when using the Event Hub-compatible endpoint? I also tried using '/' as the path and got the same outcome.

**Comment by goncalo-oliveira** [comment]
Ok, answering my own question as I found the same issue [somewhere else](https://stackoverflow.com/questions/47531609/cannot-connect-to-iot-hub-with-eventprocessorhost-in-net-core).

Essentially the Event Hub-compatible name needs to be set in the hub path, instead of the usual messages/events (for example) like in the IoT Hub.

It's a bit frustrating the documentation isn't very clear on this (or perhaps I didn't thoroughly go through it).

**Comment by VikSab** [comment]
This is still an outstanding issue - we are unable to monitor the events on the IotHub.

**Comment by d1mnewz** [comment]
Still waiting for having this implemented.
