### ISSUE TITLE
Microsoft.Azure.EventHubs.Processor reference issue on .NET Core Console App

### ISSUE THREAD

**Issue by MaherJendoubi** [Azure/azure-event-hubs-dotnet#111]
## Actual Behavior
1. 
![image](https://cloud.githubusercontent.com/assets/1798510/22614426/fdcc861e-ea81-11e6-8611-a1fb73f2687b.png)

2. 
![image](https://cloud.githubusercontent.com/assets/1798510/22614468/9fc15076-ea82-11e6-9b65-f21f36510c57.png)

## Expected Behavior
1. 
2. 

## Versions  
- OS platform and version: Microsoft Windows [version 10.0.14393]
- .NET Version:
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

- NuGet package version or commit ID: 1.0.0

**Comment by Nepomuceno** [comment]
You need to add to the imports 
"imports": ["dnxcore50", "portable-net45+win8"]

This is a problem of the Storage sdk.

I hope the teams responsible for the storage will fix that soon.

**Comment by MaherJendoubi** [comment]
@Nepomuceno Thanks!

**Comment by jtaubensee** [comment]
Yes, this is also consistent with our sample: https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/samples/SampleEphReceiver/project.json#L26
