### ISSUE TITLE
Sender issue

### ISSUE THREAD

**Issue by MaherJendoubi** [Azure/azure-event-hubs-dotnet#112]
## Actual Behavior
1. 
![image](https://cloud.githubusercontent.com/assets/1798510/22623048/cb8ef71e-eb4d-11e6-87ce-53050caf02da.png)

2. 

## Expected Behavior
1. 
2. 

## Versions  
- OS platform and version: Microsoft Windows [version 10.0.14393]
- .NET Version:
- NuGet package version or commit ID:

**Comment by jtaubensee** [comment]
@MaherJendoubi - Have you run `dotnet restore`? Any other details you can share? For a working example, check out: https://github.com/Azure/azure-event-hubs-dotnet/tree/dev/samples/SampleSender

**Comment by MaherJendoubi** [comment]
@jtaubensee when I created a new project from scratch, it worked. Thank you!

**Comment by jtaubensee** [comment]
No problem. From my experience, that means you need to run `dotnet restore`.

**Comment by MaherJendoubi** [comment]
@jtaubensee I did restore from Visual Studio but it doesn't compile.

**Comment by MaherJendoubi** [comment]
@jtaubensee I uploaded a repro here : https://github.com/MaherJendoubi/EventHubSender

**Comment by jtaubensee** [comment]
@MaherJendoubi - I saw the same thing, but it looks like you are missing this:

```json
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
```

Notice the `type` part. Or at least that is what our samples are using.

https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/samples/SampleSender/project.json#L12

**Comment by MaherJendoubi** [comment]
Perfect @jtaubensee Great to know! Thanks a lot for the help!
