### ISSUE TITLE
Delayed message (schedule message)

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-event-hubs-dotnet#114]
Including the ability to use a delay receiver this might be implemented on the Consumer side and not need to be implemented on the client side. For example I could want one consumer that only consume messages that are in the queue for more than 5 minutes.

Sample use case:
1- System **A** trigger an alert, information about this alert is put on this delay event hub.
2- System **B** has a reader with delay that only reads messages after 5 minutes in.
3- System **B** get a new message of the alert generated by **A**
4- System **B** check if the alert has been resolved already if not it escalates the alert.

I am aware that for this case that are many other architectures that could work but having this ability to delay on the receiver opens up a lot of opportunities, without adding stress to the server.

## Versions  
- Every Version.

**Comment by jtaubensee** [comment]
@Nepomuceno - Again, this is a feature that is built into Service Bus. Event Hubs is intentionally a simpler design than Service Bus, as that is what allows it to scale better.

**Comment by Nepomuceno** [comment]
@jtaubensee This could be implemented on the client side and as I posted on the other topic Service bus just do not give us enough performance.

**Comment by jtaubensee** [comment]
True - However, we havent considered doing so for the following reason. When you send a message and receive an acknowledgement, you can be assured that the message has been accepted and replicated multiple times. If something were to happen to the client when you schedule a message, that message is theoretically lost, is it hadnt already been sent to Event Hubs.

**Comment by singhania** [comment]
Currently I am doing this by blocking onEvent call until delay.
Is there any other way by which we can achieve this.

**Comment by serkantkaraca** [comment]
Event Hubs provide a stream where you can move the reader head back and forth. You can easily achieve delayed read by using low level APIs instead of processor host. Basically, create a PartitionReceiver and process anything until it hits an event which is in the last 5 minutes.
