### ISSUE TITLE
Unpredictable checkpointing of messages when receiving messages with Microsoft.Azure.EventHubs

### ISSUE THREAD

**Issue by FelixXWS** [Azure/azure-event-hubs-dotnet#119]
## Actual Behavior
1. Tested the new Microsoft.Azure.EventHubs library and the tutorial "SampleEphReceiver
2. My event hub has two partitions. Seding 100 messages but getting 200 messages on the receiver side
3. With using Microsoft.ServiceBus.Messaging everything works fine

## Expected Behavior
1. Getting only the 100 messages sent by the sender at the receiver side

## Versions  
  
- OS platform and version: Windows 7
- .NET Version: net452
- NuGet package version or commit ID: Microsoft.Azure.EventHubs.Processor version="1.0.0"

**Comment by serkantkaraca** [comment]
Are you able to reproduce it every time you run? And is it always 2 times the number of messages sent?

**Comment by FelixXWS** [comment]
Hello,

it is not always twice the number of messages sent. But it seems that the offset isn't always updated after calling the CheckpointAsync()-method. Because if I run the receiver it is always getting the same messages which should have already been checkpointed. My SimpleEventProcessor looks like this:

```
public class SimpleEventProcessor : IEventProcessor
{
        public async Task OpenAsync(PartitionContext context)
        {
            Console.WriteLine($"SimpleEventProcessor initialized. Partition: '{context.PartitionId}'");
            await Task.FromResult<object>(null);
        }

        public async Task CloseAsync(PartitionContext context, CloseReason reason)
        {
            Console.WriteLine($"Processor Shutting Down. Partition '{context.PartitionId}', Reason: '{reason}'.");
            await Task.FromResult<object>(null);
        }

        public async Task ProcessErrorAsync(PartitionContext context, Exception error)
        {
            Console.WriteLine($"Error on Partition: {context.PartitionId}, Error: {error.Message}");
            await Task.FromResult<object>(null);
        }

        public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
        {
            foreach (var eventData in messages)
            {
                var data = Encoding.UTF8.GetString(eventData.Body.Array, eventData.Body.Offset, eventData.Body.Count);
                Console.WriteLine($"Message received. Partition: '{context.PartitionId}', Data: '{data}'");
            }
            await context.CheckpointAsync();
        }
    }
```
In my blob storage where the offset is stored, it seems unpredictable if the offset is updates or not.

**Comment by serkantkaraca** [comment]
I am not able to reproduce the issue when sender and receiver run on the VS. Tried 3 times and receiver received 100 messages at all times. 

Are you running the samples from master branch or have you built your own sample projects?

**Comment by FelixXWS** [comment]
I ceated my own console (not .NET Core)  console applications. But I've just tried the sample projects from the master branch and changed nothing except my connection strings. But same result. The received events are not getting checkpointed and are received every time I start the SampleEphReceiver-example.
By the way if I try to create the the .NET Core console applications by myself and try to install the neccessary libraries with nuget I get error messages that the libraries Microsoft.Data.OData 5.7.0, Microsoft.Data.Services.Client 5.7.0,  System.Spatial 5.7.0 and Microsoft.Data.Edm 5.7.0 are not compatible with netcoreapp1.0. But I think thats another topic.

**Comment by serkantkaraca** [comment]
Can you check if the lease container being created fine? If the container is getting created fine there should be the same number of lease blobs as the number of partitions on your eventhub. I wonder if the storage writes are failing and it is not bubbling up to the client.

**Comment by FelixXWS** [comment]
At my blob container there is a folder "$Default" which contains the two blobs which correspond to my two partitions and with the name "0" and "1". Everytime I run the ReceiverSample the blobs are updated but the offset almost always stays the same.
The content of the blob look like this:
{"Offset":"186840","SequenceNumber":2203,"PartitionId":"0","Owner":"","Token":"","Epoch":74}

**Comment by serkantkaraca** [comment]
So as I understand you don't actually get all messages from sequence number 1, but you get some from the previous send.  Can you compare the lease record before and after running the sample?

**Comment by FelixXWS** [comment]
Exactly. Because some messages processed e.g. by the other example with the ServiceBus-library. And sometimes the offset is updated by the Eventhub-example. But most of the time nothing changes regarding the offset inside the lease records.
I've compared them before and after running the Receiver-example but the only thing that changes is the attribute "Epoch".
Before:
{"Offset":"186840","SequenceNumber":2203,"PartitionId":"0","Owner":"","Token":"","Epoch":80}
After:
{"Offset":"186840","SequenceNumber":2203,"PartitionId":"0","Owner":"","Token":"","Epoch":81}

**Comment by serkantkaraca** [comment]
Can you share your sample? I think it is better for me to run exactly what you are running to repro the issue.

**Comment by FelixXWS** [comment]
Not everytime becasue if I would always sent a new set of 100 messages, the messages that aren't processed would grow more and more, no matter how often I run the receiver.
Here is my code:

**SampleSender:**
```
namespace SampleSender
{
    class Program
    {
        private static EventHubClient eventHubClient;

        private const string EhConnectionString ="ConnectionString";
        private const string EhEntityPath = "EntityPath";
        
        static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();
        }

        private static async Task MainAsync(string[] args)
        {
            // Creates an EventHubsConnectionStringBuilder object from a the connection string, and sets the EntityPath.
            // Typically the connection string should have the Entity Path in it, but for the sake of this simple scenario
            // we are using the connection string from the namespace.
            var connectionStringBuilder = new EventHubsConnectionStringBuilder(EhConnectionString)
            {
                EntityPath = EhEntityPath
            };
            
            eventHubClient = EventHubClient.CreateFromConnectionString(connectionStringBuilder.ToString());
            
            await SendMessagesToEventHub(100);

            await eventHubClient.CloseAsync();

            Console.WriteLine("Press any key to exit.");
            Console.ReadLine();
        }
        // Creates an Event Hub client and sends 100 messages to the event hub.
        private static async Task SendMessagesToEventHub(int numMessagesToSend)
        {
            for (var i = 0; i < numMessagesToSend; i++)
            {
                try
                {
                    var message = $"Message {i}, Date: {DateTime.Now}";
                    Console.WriteLine($"Sending message: {message}");
                    await eventHubClient.SendAsync(new EventData(Encoding.UTF8.GetBytes(message)));
                }
                catch (Exception exception)
                {
                    Console.WriteLine($"{DateTime.Now} > Exception: {exception.Message}");
                }

                await Task.Delay(10);
            }

            Console.WriteLine($"{numMessagesToSend} messages sent.");
        }
    }
}

```
**SampleEphreceiver:**

```
namespace SampleEphReceiver
{
    class Program
    {
        private const string EhConnectionString = "EhConnectionString";
        private const string EhEntityPath = "EntityPath";
        private const string StorageContainerName = "ContainerName";
        private const string StorageAccountName = "StorageAccountName";
        private const string StorageAccountKey = "SotrageAccountKey";

        private static readonly string StorageConnectionString ="StorageConnectionString";

        static void Main(string[] args)
        {
            MainAsync(args).GetAwaiter().GetResult();
        }

        private static async Task MainAsync(string[] args)
        {
            Console.WriteLine("Registering EventProcessor...");
            var eventProcessorHost = new EventProcessorHost(
                EhEntityPath,
                PartitionReceiver.DefaultConsumerGroupName,
                EhConnectionString,
                StorageConnectionString,
                StorageContainerName);
            
            // Registers the Event Processor Host and starts receiving messages
            await eventProcessorHost.RegisterEventProcessorAsync<SimpleEventProcessor>();

            Console.WriteLine("Receiving. Press enter key to stop worker.");
            Console.ReadLine();

            // Disposes of the Event Processor Host
            await eventProcessorHost.UnregisterEventProcessorAsync();
            Console.WriteLine($"Message Count : {messageCounter}");
            Console.ReadLine();
        }
    }
public class SimpleEventProcessor : IEventProcessor
    {
        public async Task OpenAsync(PartitionContext context)
        {
            Console.WriteLine($"SimpleEventProcessor initialized. Partition: '{context.PartitionId}'");
            await Task.FromResult<object>(null);
        }

        public async Task CloseAsync(PartitionContext context, CloseReason reason)
        {
            Console.WriteLine($"Processor Shutting Down. Partition '{context.PartitionId}', Reason: '{reason}'.");
            if (reason == CloseReason.Shutdown)
            {
                await context.CheckpointAsync();
            }
        }

        public async Task ProcessErrorAsync(PartitionContext context, Exception error)
        {
            Console.WriteLine($"Error on Partition: {context.PartitionId}, Error: {error.Message}");
            await Task.FromResult<object>(null);
        }

        public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
        {
            foreach (var eventData in messages)
            {
                var data = Encoding.UTF8.GetString(eventData.Body.Array, eventData.Body.Offset, eventData.Body.Count);
                Console.WriteLine($"Message received. Partition: '{context.PartitionId}', Data: '{data}'");
            }
            await Task.FromResult<object>(null);
        }
    }
}

```

**Comment by serkantkaraca** [comment]
OK, I can see the issue. Try check-pointing after processing each batch as well. Check-pointing during graceful shutdown only isn't a good strategy.

**Comment by FelixXWS** [comment]
I've tried that and at first it worked. But when I ran the example multiple times it was the same behaviour as before. The offset is not updated. I don't know what's going wrong. But I don't think it has something to do with my eventhub or the storage account. Did you start the sender and receiver example multiple times and it always works?

**Comment by serkantkaraca** [comment]
Yes, I have run sender and receiver multiple times w/o any issues. Every run sent 100 and received 100.

Can you please run the sample instead? Again use your existing namespace and storage account.

**Comment by FelixXWS** [comment]
I have just tested both. My own example and the example from the master branch. But it stays unpredictible if the offset inside the blog container gets updated or not. Sometimes it does sometimes it doesn't. I even created a new event hub and tried another storage account but with no luck. I think I just stay with the old service bus-library because this works everytime... But many thanks for your help

**Comment by kadavkiran** [comment]
Do we have any solution for the above issue. I am getting the same issue in my application.

**Comment by serkantkaraca** [comment]
@kadavkiran, can you share your receiver code? This issue was closed because we were not able to reproduce it and reported by only once. Let's investigate your case and see if this is really same issue or not.

**Comment by kadavkiran** [comment]
The issue was with my sender code. It was sending event twice. I can confirm that check pointing is working fine with receiver code now and i am receiving the expected number of events from event HUB.
Thanks for reply @serkantkaraca .

**Comment by serkantkaraca** [comment]
I am happy to hear the issue is resolved on you side. I will keep the thread closed. Thx.
