### ISSUE TITLE
Malformed exception message for non-existent event hub

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-event-hubs-dotnet#122]
When creating an EPH with a non-existent event hub name, a malformed exception is thrown:

```
The messaging entity 'Management operation failed. status-code: 404, status-description: The messaging entity 'sb://mathewcdemo-ns.servicebus.windows.net/testhubxxx' could not be found..' could not be found.
```

Looks like the string formatting is off here - looks like the string template intended to give the simple name, but instead a full exception string is being replaced there.

Microsoft.Azure.ServiceBus.EventProcessorHost version=2.2.10

**Comment by serkantkaraca** [comment]
Thx for reporting this Mathew. I will take a look at.

**Comment by serkantkaraca** [comment]
This isn't dotnet client related but SB client. I will close this one and track internally for the SB client.

**Comment by mathewc** [comment]
Thanks, can you link me to the right repo and the new tracking issue? This will help with issues in the future, thanks.

**Comment by serkantkaraca** [comment]
This turned out to be an issue on the service side not the client. We will deploy the fix with the next upgrade. Thx for pointing.
