### ISSUE TITLE
IEventProcessor.ProcessEventsAsync get called with null IEnumerable<EventData> when InvokeProcessorAfterReceiveTimeout is set

### ISSUE THREAD

**Issue by Rattenkrieg** [Azure/azure-event-hubs-dotnet#123]
According to [this line](https://github.com/Azure/azure-event-hubs-dotnet/blob/8774bc4afbfbe44f1722ee648cbaca7ae07edede/src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs#L126) this behavior was introduced intentionally. But _WindowsAzure.ServiceBus_ library's contract was to call `IEventProcessor.ProcessEventsAsync` with empty IEnumerable in such case. This really hurts migrating. Can someone explain foundations of current implementation?

**Comment by serkantkaraca** [comment]
Thanks for reporting, I will take a look at the contract and update the thread.

**Comment by serkantkaraca** [comment]
Actually, WindowsAzure.ServiceBus has the same contract. If processorOptions.InvokeProcessorAfterReceiveTimeout is set to true then host will make empty callbacks to handler. Can you try setting processorOptions.InvokeProcessorAfterReceiveTimeout?
