### ISSUE TITLE
EventHubClient is not UT friendly.

### ISSUE THREAD

**Issue by enihcam** [Azure/azure-event-hubs-dotnet#125]
## Actual Behavior
EventHubClient cannot be mocked:
- It has no default constructor
- SendAsync is not virtual, so it cannot be overridden.
- etc.

## Expected Behavior
When project code using EventHubClient, we expect the actions on external resources can be mocked, for example SendAsync().

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by jtaubensee** [comment]
Duplicate of #24
