### ISSUE TITLE
Any plans for supporting web sockets?

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-event-hubs-dotnet#126]
What are the plans for adding in web socket support? I've got a situation where a firewall isn't letting port 5671 through, so need to use web sockets. 

I've got something working using the amqpnetlite library using wss as the scheme and setting "/$servicebus/websocket" as the path, but that doesn't appear to be the correct mechanism to connect.

**Comment by serkantkaraca** [comment]
It is in our future plans. I cannot tell an exact date yet but can say we will it support in 2 to 4 months.

**Comment by npnelson** [comment]
This would be great to have. FYI - the Microsoft.Azure.Amqp library was updated around the beginning of August with more Websocket support (v 2.1.0). https://github.com/Azure/azure-amqp/releases.

**Comment by serkantkaraca** [comment]
This is checked into dev branch. The feature will be available in release 1.0.3
