### ISSUE TITLE
Too frequent partition handovers across hosts

### ISSUE THREAD

**Issue by Rattenkrieg** [Azure/azure-event-hubs-dotnet#132]
## Actual Behavior
My _ProcessorHosts_ handovers across pool of machines (currently two) roughly every hour

## Expected Behavior
_ProcessorHosts_ should keep processing its partitions unless error (in the processor host itself) stricken

I think this is might be related to load balancing algorithm, or some errors in ampq transport libraries which leads to _ProcessorHost_ failure.
This behavior is critical since I'm maintaining lot of state in _ProcessorHost_ instances in order to turn EventHubs at-least once into exactly-once delivery guarantees.

I run smoothly using Windows.Azure.ServiceBus.EventHubs in same environment. Almost no migration of partitions across hosts.

## Versions  
- OS platform and version: Windows Server 2012
- .NET Version: 4.5.2
- NuGet package version or commit ID: 1.0.0
- Two machines sharing 128 partitions EventHub where only 12 partitions actively written

**Comment by serkantkaraca** [comment]
Can you please share any errors reported through the error handlers? We are running stress tests for hours with many instances everyday and not observing this kind of an issue. Apparently something is different in your case.

**Comment by Rattenkrieg** [comment]
Apart from "Unauthorized access" described in #134 there are
> EventHubsException: Unauthorized access. The access has expired. Resource: 'sb://.../partitions/n'
> EventHubsException: The connection was inactive for more than the allowed 120000 milliseconds and is closed by container '7A2E0A0515A9427F82D1ACF7F25A024D_G19'
> TimeoutException: The operation did not complete within the allocated time 00:01:00 for object link1035
> EventHubsException: The message container is being closed (25672). TrackingId:5a39f691-e238-4e93-9958-7b2757b58ab1_B5, SystemTracker:NoSystemTracker, Timestamp:2/24/2017 6:44:16 PM 

But those occurs far less frequently and I can't correlate any of it for sure.

**Comment by serkantkaraca** [comment]
With today's implementation host closes the partition on any type or error bubbled from Receive call. .NET client seems to do this on ReceiverDisconnectedException only. I will consider fixing this the same way as .NET client since most of the failures will be transient on the receiver and it is better to stick a partition with host longer rather than moving it around.

Again thanks for reporting this!!

**Comment by serkantkaraca** [comment]
Fix merged to dev branch,
