### ISSUE TITLE
PartitionSender.SendAsync times out when called from IIS or IIS-Express

### ISSUE THREAD

**Issue by DavePilks** [Azure/azure-event-hubs-dotnet#144]
## Actual Behavior
1. PartitionSender.SendAsync times out when called from an ASP.NET site hosted in IIS or IIS-Express
2. The exact same code executes perfectly in a console app.

I have an Azure `EventHub` that I send data to. If I use the following code in a console application (framework 4.6.1), it runs perfectly.

```csharp
eventHubClient = EventHubClient.CreateFromConnectionString(myConnString);

Console.WriteLine("Client Created");

var sender = eventHubClient.CreatePartitionSender("1");

var message = $"Message";

Console.WriteLine($"Sending message: {message}");
var eventData = new EventData(Encoding.UTF8.GetBytes(message));

if (!sender.SendAsync(eventData).Wait(TimeSpan.FromMilliseconds(10000)) )
{
   int a = 0;
}
```

However, if I put it in an `Asp.Net` application (targeting framework 4.6.1) either running in `IIS-Express` or `IIS`, it times out every time.

What am I missing here?

## Expected Behavior
1.  The SendAsync should execute and not timeout
2. 

## Versions  
- OS platform and version: Windows 20
- .NET Version: 4.6.1
- NuGet package version or commit ID: 1.0.0

**Comment by serkantkaraca** [comment]
Can you remove TimeSpan.FromMilliseconds(10000) from Wait() and try? 10 seconds might be not enough for the first send since it will involve TCP connection creation. Besides, send will honor OperationTimeout setting on the client. You don't need to specify another Timeout on top of that.

**Comment by DavePilks** [comment]
@serkantkaraca we tried removing the wait entirely but then we have no way of knowing if the operation has completed. Removing the timeout and just having a normal `Wait()` gives the same problem.

**Comment by serkantkaraca** [comment]
Don't remove the Wait(). Remove timeout from the call only. As below...

sender.SendAsync(eventData).Wait();

**Comment by jackbond** [comment]
@serkantkaraca If the first Send call could take more than ten seconds, can you guys add an OpenAsync or ConnectAsync method such that the first SendAsync call does not need to accommodate for a longer timeout?

**Comment by serkantkaraca** [comment]
I cannot really see how that will help to resolve the fact that establishing the TCP connection intermittently takes longer than 10 seconds.

**Comment by jackbond** [comment]
@serkantkaraca I guess the OpenAsync call would need to ignore the Timeout property, or take its own. Bottom line, if you're creating an EventHubClient for the lifetime of an app, you don't want to have to set it to a higher length than you really want, just to accommodate the initial call duration. If you want an example of a similar pattern, just look DocumentDb's DocumentClient. OpenAsync also allows you to validate that you've provided the correct connection string information, which you don't want to do inline with every SendAsync call.

**Comment by serkantkaraca** [comment]
Thanks for the recommendation. I will consider adding some buffer for OpenAsync call such as it can take the minimum of 60 seconds or the operation timeout provided on the client. I think this should also address your issue.

**Comment by serkantkaraca** [comment]
PR published at https://github.com/Azure/azure-event-hubs-dotnet/pull/154

**Comment by serkantkaraca** [comment]
The fix is merged into dev branch.
