### ISSUE TITLE
Azure Storage lease container name with dash not valid

### ISSUE THREAD

**Issue by gambrose** [Azure/azure-event-hubs-dotnet#151]
## Actual Behaviour
1. using a storage container name with a dash in it e.g. "my-container" throws exception.

## Expected Behaviour
1. Dashes are allow in container names and so should be valid.

## Versions  
- OS platform and version: Win 10
- .NET Version: 4.5.1
- NuGet package version or commit ID: 1.0.1

**Comment by serkantkaraca** [comment]
Thanks for reporting this. I will check and then update the thread.

**Comment by serkantkaraca** [comment]
Actually we use lease container names with dash in our unit tests. Here is an example:

''
            // Generate a new lease container name that will use through out the test.
            string leaseContainerName = Guid.NewGuid().ToString();

            // Consume all messages with first host.
            // Create host with 'firsthost' prefix.
            var eventProcessorHostFirst = new EventProcessorHost(
                "host1",
                string.Empty,
                PartitionReceiver.DefaultConsumerGroupName,
                this.EventHubConnectionString,
                this.StorageConnectionString,
                leaseContainerName,
                "firsthost");
            var runResult1 = await RunGenericScenario(eventProcessorHostFirst);
''

**Comment by gambrose** [comment]
My bad, I thing I reported this wrong then.

Playing around with this again I found that I can have a dash in the `leaseContainerName` name but if you have a dash at the end of `storageBlobPrefix` then I get an `ArgumentException` for param `leaseContainerName` "Azure Storage lease container name is invalid"

I guess I was confused as the error was talking about the `leaseContainerName`.

**Comment by gambrose** [comment]
OK, I now see what the issue is the overload that takes a `storageBlobPrefix` has an extra parameter `hostName` as the first parameter.

Having the `EventProcessorHost` with multiple overloads which are just different number of strings that are not even consistency ordered makes this a very hard api to use.
