### ISSUE TITLE
Question on AsyncLock possibly causing deadlock

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-event-hubs-dotnet#152]
I noticed the AsyncLock code and have a question about how it works.

It looks like the LockRelease can be cached for the situation when the WaitAsync completes immediately. 

However unless I have misunderstood things, it will only release the Semaphore the first time around, as releasing the semaphore causes the disposed flag to be set. 

eg
First time
WaitAsync completes immediately
Cached lockRelease is returned
Cached lockRelease is disposed, releasing the semaphore and setting the disposed flag

Second time
WaitAsync completes immediately
Cached lock release is returned
Cached lockRelease is disposed, but as the disposed flag is already set, **does not release the semaphore**

Does this make sense?

**Comment by serkantkaraca** [comment]
Thanks for reporting this. I will check the code and update the thread. Btw, were you able to reproduce a deadlock or this is from just code review?

**Comment by nrandell** [comment]
This was just from a code review

**Comment by serkantkaraca** [comment]
Ok, I have review the code. One thing you were missing is that LockRelease is a struct. When a struct used in a using statement it will be boxed. So next time the same struct boxed, disposed bool will still be false. It will never retain its true value. This solution works well, maybe we should remove disposed bool completely since it has no use.

**Comment by nrandell** [comment]
Ok - interesting. I saw the LockRelease was a struct from the comment earlier on in the code about not allocating. But hadn't realised the it would be boxed in a using statement!
I guess removing the disposed bool will make this easier to read! Thanks for looking at it.

**Comment by serkantkaraca** [comment]
Related PR is at https://github.com/Azure/azure-event-hubs-dotnet/pull/153
