### ISSUE TITLE
Two get getting started links on Readme.MD are broken. 

### ISSUE THREAD

**Issue by mstrother** [Azure/azure-event-hubs-dotnet#159]
The two links under **Getting Started** are broken. Specifically,  _Get started sending messages to Event Hubs in .NET Core_ , and _Get started receiving messages with the EventProcessorHost in .NET Core_.

**Comment by jtaubensee** [comment]
@mstrother - Thanks for pointing this out. I've updated the readme with the following commit: b29ab0b70e7bbbcd8e88d64bcd3c508f96266d67
