### ISSUE TITLE
Avoid multiple unrelated assumptions in a single test case

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#18]
An example would be `ProcessorHostEntityPathSetting` test validating multiple scenarios:
1. [Entity path provided in the connection string](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L60)
2. [Entity path provided in the eventHubPath parameter](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L70)
3. [The same entity path provided in both eventHubPath parameter and the connection string](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L81)
4. [Entity path not provided in both eventHubPath and the connection string](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L92)
5. [Entity path conflict](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L110)

**Comment by serkantkaraca** [comment]
All are related actually. The test is focusing on different usage cases of both entityPath parameter and the connection string.

**Comment by SeanFeldman** [comment]
You're absolutely correct, they are related and focus on different use cases for `entityPath` parameter. That's why it would make sense to keep them under a single `roof` (ie Test fixture), but as isolated tests. Each test should really test one thing at a time ([SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle)). When a test is failing, you want to read the fixture/test name to understand the context rather than going through various options why it could have failed. I'll try to refactor this code tonight to elaborate on the idea 😄

**Comment by jtaubensee** [comment]
Need to reevaluate if this is still an issue as the tests have changed greatly since the end of October.
