### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by cwe1ss** [Azure/azure-event-hubs-dotnet#184]
I've asked this a few times already in #134 but since there's been no progress I'm creating a new issue.

#134 is a bug which leads to a unstable behavior of this [GA released](https://azure.microsoft.com/en-us/blog/event-hubs-dotnet-standard-client-reaches-ga/) library. This bug has been fixed two months ago but there hasn't been a release since then.

So PLEASE release a new version asap - I really don't want to compile my own version of this library.

**Comment by sjkwak** [comment]
We will ship new version early next week.

**Comment by cwe1ss** [comment]
Thank you very much!!!
