### ISSUE TITLE
Get started links are not accessible and error when connection to iot hub

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-event-hubs-dotnet#185]
I am trying to access the get started link so i can use the new library to read messages from iot hub. 
So i am having an issue to creating an object from the iothub connection string. here is the code:

```
 connectionString = appSettings["iotHubConn"];
 consumerGroupName = appSettings["consumerGroupName"];

 eventHubClient = EventHubClient.CreateFromConnectionString(connectionString);
```

The error i am getting is:
Illegal connection string paramter name 'Host Name'.

I copied the connection string from the iot hub, it is as follows:

 "iotHubConn": "HostName=MYIOTHUB.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=KEY",
  
Any thoughts how to fix this issue?

Thanks a lot.

**Comment by sjkwak** [comment]
Please take a look at the link to set up properly - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin

**Comment by melzoghbi** [comment]
Hi @sjkwak 

I am getting this error when i modify the scheme of the iot hub connection string.

System.UriFormatException: 'Invalid URI: The format of the URI could not be determined.'

Here is my updated iot connection string as per the article you referred to:

"iotHubConn": "Endpoint=MYIOTHUB.servicebus.windows.net;SharedAccessKeyName=iothubowner;SharedAccessKey=eHCww8OxnKDqR7+U189pZyrqWNvXBZlGnpBnasirLIQ=",
   

Let me know.

**Comment by serkantkaraca** [comment]
Can you try adding sb:// as the URI scheme.

**Comment by melzoghbi** [comment]
@sjkwak, It had already the uri scheme when i initially used it as a copy from the azure portal.

**Comment by serkantkaraca** [comment]
I mean add scheme to this connection string as below.

"Endpoint=sb://MYIOTHUB.servicebus.windows.net;SharedAccessKeyName=iothubowner;SharedAccessKey=-secret removed-",

**Comment by melzoghbi** [comment]
I get an error as specified in my initial post when i use full connection with uri scheme.

**Comment by serkantkaraca** [comment]
Here is a valid connection string for the client. Can you replace the parts with your settings?

Endpoint=sb://myehnamespace.servicebus.windows.net/;SharedAccessKeyName=SasKeyName;SharedAccessKey=SasKey;Path=myeh-pathtoyoureh

**Comment by melzoghbi** [comment]
Here is a detailed error:

System.ArgumentException occurred
  HResult=0x80070057
  Message=**The argument EntityPath is null or white space.**
Parameter name: EntityPath
  Source=Microsoft.Azure.EventHubs
  StackTrace:

**Comment by serkantkaraca** [comment]
My bad, please replace Path with EntityPath in the connection string and try again.

EntityPath=myeh-pathtoyoureh

**Comment by melzoghbi** [comment]
This works! Thanks a lot @serkantkaraca for your instant support.

**Comment by gideondsouza** [comment]
Hi,
Could anyone give me any information on what the entity path really is? Where would I find the entity path.

**Comment by serkantkaraca** [comment]
EntityPath is the name of the Event Hub.
