### ISSUE TITLE
Prefer Assert.Throws to try/catch

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#19]
[`Assert.Throws` (or Record.Exception)](https://xunit.github.io/docs/comparisons.html#attributes) is more aligned with testing than `try`/`catch` blocks. Example [here](https://github.com/Azure/azure-event-hubs-dotnet/blob/124148840a2dfaa881527d6432a224de4c197594/test/Microsoft.Azure.EventHubs.Processor.UnitTests/EventProcessorHostTests.cs#L112).

**Comment by SeanFeldman** [comment]
I've added a few examples in PR #15, this [commit](https://github.com/Azure/azure-event-hubs-dotnet/pull/15/commits/76cc0b48437fec120aed39e6c4391c184257f221)

**Comment by serkantkaraca** [comment]
Thx for recommendation. Code is cleaner this way.
