### ISSUE TITLE
How to build the .net src in Visual Studio 2017

### ISSUE THREAD

**Issue by JeffreyZZ** [Azure/azure-event-hubs-dotnet#191]
## Actual Behavior
1. I suppose that this project could be built in Visual Studio 2017 but I didn't see any guidance on this. 
2. I ran into the same build issue documented at https://stackoverflow.com/questions/43758135/msbuild-imported-project-sdk-props-was-not-found but didn't find a solution to it. 

## Expected Behavior
1. Provide some guidance on how to build the src.
2. 

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
Sure, we can add guidance to readme. Btw, are you hitting any issues while building on VS 2017?

**Comment by JeffreyZZ** [comment]
Sorry for the delayed response. I tried to open src\Microsoft.Azure.EventHubs.sln in Visual Studio Professional 2017 (Version 15.2 (26430.16) Release) in Administrator Mode. The Output shows the following error messages under Package Manager, where the solution failed to resolve the referenced NuGet packages. Did I miss any step to setup my local dev environment?


Restoring NuGet packages...
Unable to resolve 'WindowsAzure.Storage (>= 8.1.1)' for 'UAP,Version=v10.0'.
Unable to resolve 'Microsoft.Extensions.PlatformAbstractions (>= 1.1.0)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.3)' for 'UAP,Version=v10.0'.
Unable to resolve 'Newtonsoft.Json (>= 10.0.2)' for 'UAP,Version=v10.0'.
Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'System.Runtime.Serialization.Primitives (>= 4.3.0)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.3)' for 'UAP,Version=v10.0'.
Unable to resolve 'Microsoft.NETCore.Platforms (>= 1.1.0)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'System.Reflection.TypeExtensions (>= 4.3.0)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'xunit (>= 2.2.0)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'WindowsAzure.Storage (>= 8.1.1)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'Microsoft.NET.Test.Sdk (>= 15.0.0)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'Newtonsoft.Json (>= 10.0.2)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'WindowsAzure.Storage (>= 8.1.1)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'System.Runtime.Serialization.Primitives (>= 4.3.0)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'Newtonsoft.Json (>= 10.0.2)' for '.NETFramework,Version=v4.6'.
Unable to resolve 'System.Reflection.TypeExtensions (>= 4.3.0)' for '.NETStandard,Version=v1.3'.
Unable to resolve 'Microsoft.Extensions.PlatformAbstractions (>= 1.1.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'WindowsAzure.Storage (>= 8.1.1)' for '.NETFramework,Version=v4.5.1'.
Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Newtonsoft.Json (>= 10.0.2)' for '.NETFramework,Version=v4.5.1'.
Unable to resolve 'Microsoft.NETCore.Platforms (>= 1.1.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Microsoft.NETCore.App (>= 1.0.4)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'xunit (>= 2.2.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Microsoft.NET.Test.Sdk (>= 15.0.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'WindowsAzure.Storage (>= 8.1.1)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Newtonsoft.Json (>= 10.0.2)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'System.Runtime.Serialization.Primitives (>= 4.3.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'System.Reflection.TypeExtensions (>= 4.3.0)' for '.NETCoreApp,Version=v1.0'.
NuGet package restore failed.
Time Elapsed: 00:00:04.0703632
========== Finished ==========

**Comment by serkantkaraca** [comment]
Thanks for the pointer. I will update the readme with what SDKs are needed to compile.

For your case, please run Visual Studio Installer for 2017 and add .Net Core SDK.

**Comment by serkantkaraca** [comment]
Sent a PR for readme update. https://github.com/Azure/azure-event-hubs-dotnet/pull/199

**Comment by serkantkaraca** [comment]
Merged into master
