### ISSUE TITLE
Default EventProcessorHost with AzureStorage is not extensible or configurable.

### ISSUE THREAD

**Issue by adminnz** [Azure/azure-event-hubs-dotnet#201]
When using the EventProcessorHost according to all the examples on an EventHub with 4 partitions it makes **96 calls every minute** to the Azure Blob Store. (This is when there are no Events being consumed.)
This works out to 138,240 calls every day which is excessive.

I thought this would be a simple fix by increasing the LeaseDuration and LeaseRenewInterval from their defaults of 30 and 10 seconds respectively, to something like 5 minutes & 1 minute.
But when looking into the code the AzureStorageCheckpointLeaseManager is marked as sealed ([please follow your own guidelines on sealing!](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/sealing)).
And whats even worse is the LeaseRenewInterval & LeaseDuration are not configurable because they are referencing static fields (which in combination of the sealed class means they cannot be changed).

Possible Fixes:

- Unseal all classes that shouldn't be sealed (which is basically every class in this library apart from /Amqp/*

- Provide configurable options that include the Storage Connection String, Lease Container Name, BlobPrefix, LeaseDuration & LeaseRenewInterval.

**Comment by serkantkaraca** [comment]
Thx for pointing. We will fix these issues in the next release.

**Comment by serkantkaraca** [comment]
Fix merged to dev branch. We will include the fix in our next client release.
