### ISSUE TITLE
Handle MessageSizeExceededException correctly using .Net Standard

### ISSUE THREAD

**Issue by sergsalo** [Azure/azure-event-hubs-dotnet#204]
I"m using Microsoft.Azure.EventHubs (1.0.3) library to send data to EventHub. I send batch of EventData using overload for SendAsync. Sometimes it throws MessageSizeExceededException. So, what is the right way to figure out the size of EventData? I use next: 
 ```csharp
           var batchList = new List<EventData>();
            long batchSize = 0;
            foreach (var item in data)
            {
                var eventData = new EventData(Encoding.UTF8.GetBytes(data));
                var eventDataSize = eventData.Body.Count;
                if (batchSize + eventDataSize > 256000)
                {
                    await mEventHubClient.SendAsync(batchList);
                    batchList = new List<EventData> { eventData };
                    batchSize = eventDataSize;
                }
                else
                {
                    // Add the EventData to the current batch
                    batchList.Add(eventData);
                    batchSize += eventDataSize;
                }
            }
            await mEventHubClient.SendAsync(batchList);
````

Is it a correct way to deal with this issue?

**Comment by serkantkaraca** [comment]
Try using EventDataBatch API which addresses this issue. https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/test/Microsoft.Azure.EventHubs.Tests/Client/ClientTestBase.cs:103

Please let me know if you hit any issues.

**Comment by sergsalo** [comment]
great, that seems like it solved the issue! thanks!
