### ISSUE TITLE
NuGet pre-release for .NET Standard 2.0

### ISSUE THREAD

**Issue by matthijskoopman** [Azure/azure-event-hubs-dotnet#209]
We have recently moved our entire stack from .NET Core 1.1 and .NET Standard 1.6.1 to version 2.0
We would like to move the last bits regarding Azure Event Hubs to version 2.0 as well.

We are wondering if a pre-release version of the upgraded package will be available on NuGet anytime soon?

Regards,
Matt

**Comment by sjkwak** [comment]
Hi @matthijskoopman, we're planning to release new version in a week or so and the new version will move to .NET Standard 2.0.

**Comment by matthijskoopman** [comment]
Thanks @sjkwak

**Comment by sjwaight** [comment]
Do we have a rough timeline for a release for this?

**Comment by sjkwak** [comment]
Hi @sjwaight, our release schedule is getting delayed due to other urgent stuffs, but we are trying to release new version this month.

**Comment by sjwaight** [comment]
Where are we at with this? I've delayed work on a feature that requires this in 2.0. If it's not happening in the next couple of weeks I'm either having to implement my EH client or look at another solution.

**Comment by sjkwak** [comment]
Sorry for the late response. We're going to release new version next week.

**Comment by serkantkaraca** [comment]
1.1.0 is released with 2.0 support
