### ISSUE TITLE
EventProcessorOptions.InitialOffsetProvider return null leads to exception

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-event-hubs-dotnet#211]
```csharp
EventProcessorOptions options = new EventProcessorOptions();
options.InitialOffsetProvider = (partitionId) => null;
```

## Actual Behavior
Exception: Error on Partition: 1, Error: Unexpected object type returned by user-provided initialOffsetProvider

## Expected Behavior
According to the comment on the property, it should fall back to use the default:
        //
        // Summary:
        //     Get or sets the current function used to determine the initial offset at which
        //     to start receiving events for a partition.
        //     **A null return** indicates that it is using the internal provider, which uses the
        //     last checkpointed offset value (if present) or StartOfSTream (if not).

## Versions  
- OS platform and version: 1709 (16299.19)
- .NET Version: .NET Standard 1.3 (Referenced by UWP)
- NuGet package version or commit ID: v1.0.3

**Comment by serkantkaraca** [comment]
Thx for reporting. I will work on the issue and update the thread.

**Comment by serkantkaraca** [comment]
It seems the description is deceptive. I will fix that.
The valid values you can return for the provider call are DateTime and String.

**Comment by serkantkaraca** [comment]
Submitted a PR https://github.com/Azure/azure-event-hubs-dotnet/pull/224
