### ISSUE TITLE
Creating EventHubsConnectionStringBuilder with sharedAccessSignature always crashes

### ISSUE THREAD

**Issue by alexsorokoletov** [Azure/azure-event-hubs-dotnet#218]
## Actual Behavior
1. create new EventHubsConnectionStringBuilder with sharedAccessSignature overload and non-empty shared access signature string.
2. ctor throws ArgumentException

## Expected Behavior
1. Should create a new EventHubsConnectionStringBuilder
2. 

## Versions  
- OS platform and version: MacOS
- .NET Version: 2.0.0
- NuGet package version or commit ID: NuGet 1.0.3

##
Top of the stack trace:

```
System.ArgumentException: The argument sharedAccessSignature is null or white space.
Parameter name: sharedAccessSignature
  at Microsoft.Azure.EventHubs.EventHubsConnectionStringBuilder..ctor (System.Uri endpointAddress, System.String entityPath, System.String sharedAccessSignature, System.TimeSpan operationTimeout) 
```

See line 119 here for a code reference https://github.com/Azure/azure-event-hubs-dotnet/blame/dev/src/Microsoft.Azure.EventHubs/Primitives/EventHubsConnectionStringBuilder.cs#L119

**Comment by serkantkaraca** [comment]
Thanks for reporting this. We will have the fix in the next release. Until then you can provide the SharedAccessSignature in the connection string overload: 

        /// <summary>
        /// ConnectionString format:
        /// Endpoint=sb://namespace_DNS_Name;EntityPath=EVENT_HUB_NAME;SharedAccessKeyName=SHARED_ACCESS_KEY_NAME;SharedAccessKey=SHARED_ACCESS_KEY
        /// </summary>
        /// <param name="connectionString">Event Hubs ConnectionString</param>
        public EventHubsConnectionStringBuilder(string connectionString)

**Comment by serkantkaraca** [comment]
PR for fix here: https://github.com/Azure/azure-event-hubs-dotnet/pull/220

**Comment by alexsorokoletov** [comment]
@serkantkaraca thank you for agile response.
SharedAccessSignature can't be parsed from connection string (at least how I understand).
Here is an example what we get from SASTokenProvider 

```
SharedAccessSignature sr=https%3a%2f%2fab-some-qa-namespace.servicebus.windows.net%2fab-some-qa-events%2fPublishers%2fcab15879-6356-4211-bdd1-244acc0c4a48&sig=Gx7eTn5eTe9R0%2bI30BDx%2fViG2olbx7rzyMpJjOzEGlY%3d&se=1512278480&skn=Sender
```

It contains multiple `=` so the `ParseConnectionString` can't handle that.

**Comment by alexsorokoletov** [comment]
I was able to send locations from Xamarin.Android to EventHub using this sdk. However, sometimes I face this problem (maybe related?) https://github.com/Azure/azure-amqp/issues/82

**Comment by serkantkaraca** [comment]
Fix checked-in.

**Comment by alexsorokoletov** [comment]
@serkantkaraca Wondering if you'd be able to check the issue in azure-amqp and then build newer nuget version for event hub and amqp dependency update. We would appreciate that in our production app

**Comment by serkantkaraca** [comment]
Parser uses ';' as delimiter, and we already have a unit test for that. So, it should work. For the new client release, I want to get couple pending PRs in first, you can see them on the PR tab. I can target new release in 2 weeks time frame; 1.1.0 released yesterday. So bad I couldn't get this fix in :( Let me see what I can do.
