### ISSUE TITLE
Argument validation error in EventHubsConnectionStringBuilder(Uri, string, string, TimeSpan)

### ISSUE THREAD

**Issue by jweathers** [Azure/azure-event-hubs-dotnet#227]
## Description
Validation in EventHubsConnectionStringBuilder(Uri endpointAddress, string entityPath, string sharedAccessSignature, TimeSpan operationTimeout) validates the SharedAccessSignature property and not the sharedAccessSignature argument value.

## Actual Behavior
1. Ctor called with valid values
2. Argument null exception thrown for sharedAccessSignature argument

## Expected Behavior
1. Ctor called with valid values
2. Ctor completes successfully

## Versions  
- OS platform and version: Win 7
- .NET Version: 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.EventHubs v1.1.0

**Comment by serkantkaraca** [comment]
Actually this is already fixed. See here: https://github.com/Azure/azure-event-hubs-dotnet/commit/0246a9524060dfefc2efe0a971312ffeabbcc0cc

The fix will be part of our next release.

**Comment by jweathers** [comment]
Thank you
