### ISSUE TITLE
IPartitionReceiveHandler.ProcessEventsAsync keeps being called with null as parameter instead of the IEnumerable<EventData>

### ISSUE THREAD

**Issue by andrecarlucci** [Azure/azure-event-hubs-dotnet#231]
## Actual Behavior
`IPartitionReceiveHandle.ProcessEventsAsync` keeps being called with **null** as parameter instead of the `IEnumerable<<EventData>`

It receives one single event and then loops with null over and over.

Here is my code:

```cs
var client = EventHubClient.CreateFromConnectionString(_connectionString);
            var info = await client.GetRuntimeInformationAsync();

            var receiver = client.CreateReceiver(PartitionReceiver.DefaultConsumerGroupName, 
                                                 info.PartitionIds[0], 
                                                 null);
            receiver.SetReceiveHandler(new PartitionReceiveHandler());
```

```cs
public class PartitionReceiveHandler : IPartitionReceiveHandler {
        public int MaxBatchSize { get; }

        public async Task ProcessErrorAsync(Exception error) {
            Console.WriteLine("Error!: " + error);
        }

        public async Task ProcessEventsAsync(IEnumerable<EventData> events) {
            if(events == null) {
                Console.WriteLine("Null :(");
                return;
            }
            foreach (var msg in events) {
                Console.WriteLine($"Message: Seq: {msg.SystemProperties.SequenceNumber} OffSet: {msg.SystemProperties.Offset}");
            }
        }
    }
```

## Versions  
- OS platform and version: Windows 10
- .NET Version: .net core
- NuGet package version or commit ID: 1.1.0

**Comment by serkantkaraca** [comment]
Null receive means there are no events to deliver. You should omit null callbacks for now. In the near future we will add a knob to control this behavior as in EventHubs Java clients. I am marking this as feature request.

**Comment by andrecarlucci** [comment]
Hi @serkantkaraca , thanks for the answer.

Yes, null is confusing, maybe an empty list would be better and avoid errors. 
Anyway, I think it would be better to just fire the event if there is something useful for the user. 

There is another problem: I have events, hundreds of them, but the method is being called only once, and only with the first event.

If I use the `receiver.ReceiveAsync()` I can get them all.

**Comment by serkantkaraca** [comment]
Can you trace the errors in the error handler? I believe the receiver pump is failing due to some errors after receiving the very first message. If you can provide a sample code, that would also help me to understand what is going wrong.

**Comment by andrecarlucci** [comment]
The `ProcessErrorAsync` is never called :(
I also get no errors on VS Output Window.

Here is the source code:
https://github.com/andrecarlucci/AzureEventHubSample

**Comment by serkantkaraca** [comment]
OK, I see the issue. MaxBatchSize default value of 0 is the reason for no-receive issue. Set it in the constructor of the handler. I will submit a fix to default it to a non-zero value.

        public PartitionReceiveHandler()
        {
            this.MaxBatchSize = 10;
        }

**Comment by andrecarlucci** [comment]
I confirm that setting MaxBatchSize to any value other than zero makes it work :)
I agree that a default number is necessary, but maybe it is a good idea to make zero = max (whatever max is).

Thank you for the fix. Cheers!

**Comment by serkantkaraca** [comment]
DefaultBatchSize PR is here: https://github.com/Azure/azure-event-hubs-dotnet/pull/235

**Comment by serkantkaraca** [comment]
This is merged now
