### ISSUE TITLE
Initial offset provider ignored

### ISSUE THREAD

**Issue by sorenhoyer** [Azure/azure-event-hubs-dotnet#233]
**Copied from @PeterKelecom over at**

https://github.com/Azure/azure-event-hubs/issues/256 

_"I've set my function to return the current datetime so that the processor will only start processing the new incoming messages. However, the processor still starts from the start of the stream.
Code below:

```
EventProcessorHost host = new EventProcessorHost(eventHubName, consumerGroupName, eventHubConnectionString.toString(), storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setInitialOffsetProvider((partitionId) -> { return Instant.now();});
try {
host.registerEventProcessorFactory(factory, options).get();
}
```
"_

**Problem:**

_"Upon further testing, this only works the first time, when the container doesn't exist. After that, the container is created, contains a folder for the consumergroup and in that folder has checkpoint data, even though the processor never checkpoints. On restart of the processor, it starts processing messages from the start of the queue."_

I face exactly the same issue. If I change the storage container name it works only the first time.

Some work was done on this by @JamesBirdsall on [september 16 and 21 in 2016](https://github.com/Azure/azure-event-hubs-java/commits/dev?after=dd15dd49dbfd77ce44fc21cc77201ad8781d00b6+139) - for the java version. Looking at the code it would seem as if the commit from sept. 21 wasn't added to the c# code. Since I cannot build this repo due to https://github.com/Azure/azure-event-hubs-dotnet/issues/232 , I cannot check if this fixes it: https://github.com/Azure/azure-event-hubs-java/commit/353fb37d1dcab604b62ccab6b34407b36baae2d1

**Comment by serkantkaraca** [comment]
"This only works the first time, when the container doesn't exist."

Above statement is a feature not a bug. Initial offset provider only rules at the first time before storage containers are created. In order to start the receivers from a new position you need to change lease container name. 

Please let me know if you hit any issues or have any other questions.

**Comment by JamesBirdsall** [comment]
The problem on the Java side is that it was creating the checkpoint holders (blobs) in storage with default values (start of stream) rather than marking them as uninitialized*. The result was that even when the user never checkpointed, and expected to always use the initial offset provider, there was a valid (default) checkpoint in storage which would override their initial offset provider.

I thought this change got ported to the .net client but the problem description sounds like it didn't.

*Because we use the same blobs for leases and checkpoints, due to backward compatibility, the blobs must always exist. If checkpoints were separate, then we could simply not create a checkpoint blob unless the user called checkpoint and life would be simpler, but that option is not available.

**Comment by sorenhoyer** [comment]
@serkantkaraca The problem is that there is no way to use InitialOffsetProvider , since the first time you run the EventProcessorHost it automatically sets a checkpoint for you. This is of course not the intended behavior. To mention a real use case, I need to fetch live data so I need to be able to do `InitialOffsetProvider = (partitionId) => DateTime.UtcNow` - as it stands right now, I can use it once, by supplying a leaseContainerName that doesnt exist. The first time the EventProcessorHost runs however, it automatically creates a checkpoint which is favored over the InitialOffsetProvider

**Comment by serkantkaraca** [comment]
This is the default behavior inherited from .Net client. .Net client also creates leases as part of host initialization. I am not sure why Java decided to change this.

**Comment by sorenhoyer** [comment]
Thank you @JamesBirdsall for recognizing it for what it is - a bug, not a feature :-) 

Comparing the commits you made in the java client with the .net code, it would seem as if it's just commit 353fb37 that needs to be implemented - basically just one line, right?

Since I cannot build this repo myself, I hope one of you will look into this and fix it in a PR.

**Comment by sorenhoyer** [comment]
@serkantkaraca tell me how to deal with realtime data fetching then, using the EventProcessorHost if it always sets a checkpoint, and begins from where it left off. What it actually does is, it hangs and overflows with (old) data which I have no interest in. Why not make it a little flexible...

**Comment by serkantkaraca** [comment]
We will discuss and update you. As I mentioned in the other thread you opened, you should be able to build at least the .Net assembly. For other targets you need to install the corresponding SDK like .NEt Standard SDK or UAP SDK.

**Comment by sorenhoyer** [comment]
Now running it locally changing only this line of code: https://github.com/Azure/azure-event-hubs-java/commit/353fb37d1dcab604b62ccab6b34407b36baae2d1
I can verify that it's working as I'd expect. Let me know if you want me to create a PR for this

**Comment by serkantkaraca** [comment]
I have tried the scenario on both .NET and .Net Standard clients. I need to make this correction. Current behavior in all clients are the same. Initial offset provider is respected until Checkpoint is called. Once checkpoint is called leases are written with offsets and after that lease values are respected.

Can you run your code w/o check pointing? By modifying initial offset provider you should be able to start reading wherever you want every time you start your host.

**Comment by sorenhoyer** [comment]
I'm using .net core 2. I've made this change https://github.com/sorenhoyer/azure-event-hubs-dotnet/commit/2c7d7e243d31479a03c5b38c8389dfa79ffe660e in my fork and running it locally with this change seems to be working.

**Comment by serkantkaraca** [comment]
As I mentioned the current behavior is already what you are asking for. If checkpoint isn't called before, initial offset provider is always respected. We might be talking about different things.  Can you provide me a small repro of the issue?

**Comment by sorenhoyer** [comment]
@serkantkaraca here's an example you can run by specifying the command line args:

`dotnet run [eventHubPath] "[ehConnectionString]" [leaseContainerName] [storageAccountName] "[storageAccountKey]"
`
And just to be clear. I do not with to use checkpoints. Everytime I start the EventProcessor it should fetch  live data from `InitialOffsetProvider = (partitionId) => DateTime.UtcNow` - Not just the first time I change the leaseContainerName - when I start up the EventProcessor the next day, it should not care about past data, but start from the present - always.

Yesterday [I noticed this constructor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessorhost.-ctor?view=azure-dotnet#Microsoft_Azure_EventHubs_Processor_EventProcessorHost__ctor_System_String_System_String_System_String_System_String_Microsoft_Azure_EventHubs_Processor_ICheckpointManager_Microsoft_Azure_EventHubs_Processor_ILeaseManager_) where you can create your own ICheckpointManager and ILeaseManager, but if you really do not care about checkpoints and leases, but just want the present events, how would the simplest dummy implementation for those look like?

**Comment by serkantkaraca** [comment]
Thanks Soren. The sample code you shared still does check-pointing. Basically don't call context.CheckpointAsync(); since you don't want to check-point. If you checkpoint the initial offset provider won't be respected. That is not a bug.

**Comment by sorenhoyer** [comment]
Ahh sorry I didn't see this before.

Simply changing `return context.CheckpointAsync();` to `Task.FromResult(0)` seems to work.

Thanks a lot for making me realize this!

**Comment by serkantkaraca** [comment]
I happy to hear it works now. Please let us know if you hit any issues.

**Comment by maniraj1234** [comment]
Is there a way to provide InitialOfsetProvider = Time.UTCNow - 30min;
and on service restart, it should be able to read data from Min(checkpointIndex, InitialOffsetProvider)?

**Comment by sujithchenanath909** [comment]
How to set initialOffset value in java client?
