### ISSUE TITLE
When we migrate Azure storage classic to ARM events are not triggering

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [Azure/azure-event-hubs-dotnet#234]
## Actual Behavior
1. When we migrate Azure storage classic to ARM events are not triggering
2. 

## Expected Behavior
1. 
2. 

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
How is this related to Event Hubs client?

**Comment by serkantkaraca** [comment]
Question is not related to this repository.
