### ISSUE TITLE
Correlation Id not received from IotHub EH endpoint

### ISSUE THREAD

**Issue by aloysiustany** [Azure/azure-event-hubs-dotnet#242]
## Actual Behavior
I am setting the CorrelationId property of Microsoft.Azure.Devices.Client.Message from the IotHub device end. But there is no way I am able to receive the same CorrelationId on the service side IoTHub EH endpoint.

This does not look to be an issue in Microsoft.Azure.Devices.Client as earlier when I was using Microsoft.ServiceBus.Messaging.EventData, I was able to get the CorrelationId from SystemProperties of EventData. But, this is not the case with Microsoft.Azure.EventHubs.EventData 

## Expected Behavior
I should be able to retrieve the device set CorrelationId through SystemProperties or Properties Dictionary of Microsoft.Azure.EventHubs.EventData

## Versions  
- .NET Version: 4.5.1
- NuGet package version or commit ID:
Microsoft.Azure.EventHubs version 1.0.3
Microsoft.Azure.EventHubs.Processor version 1.0.1
Microsoft.Azure.Devices.Client version 1.6.1
Microsoft.Azure.Devices.Shared 1.4.0

**Comment by serkantkaraca** [comment]
That is true, new client doesn't support some of the system properties that .Net client supports. I am marking this request as enhancement request to track it.

**Comment by serkantkaraca** [comment]
Actually I realized this is already addressed recently and fix is merged in to dev branch. Here it is: https://github.com/Azure/azure-event-hubs-dotnet/commit/56a65f761e18eb9deeae15baa5dd76758099779b

The fix will be in our next client release.

**Comment by aloysiustany** [comment]
Thanks for the reply. Do we have a approx. date for next release ?

**Comment by serkantkaraca** [comment]
It seems we don't have any pending high priority fixes. It's OK to say new release will happen in the next 2 weeks. Thx.

**Comment by ferantivero** [comment]
@serkantkaraca could it be still in progress for .NET Core?

**Comment by serkantkaraca** [comment]
2.1 release has the fix. You should be able to receive those in SystemProperties property of EventData.

**Comment by ferantivero** [comment]
thanks for replaying @serkantkaraca, just in case you could double check this, I performed a comparison SxS (.NET Fwk and .NET core using 2.1) and I'm pretty much sure I'm seeing diff amount of System Properties, and one of the missing props would be correlation id.

**Comment by serkantkaraca** [comment]
SystemProperties is a simple Dictionary object now as in old .NET client. I don't know why it is not working the same way.

Do you mind providing a small app to reproduce the issue? I believe it should involve IOT client sender and then EH client receiver. If I can debug, I can identify the issue and submit a fix.

**Comment by ferantivero** [comment]
thanks for reopening this @serkantkaraca, I've just open a PR (#302) for this. To reprod it, please let's take a look at  https://github.com/Azure/azure-event-hubs-dotnet/pull/302/files#diff-b58f6b4f4260eef634fa15f7154417d7R21

**Comment by serkantkaraca** [comment]
Thx! I have merged the fix.
