### ISSUE TITLE
Missing writable PartitionKey in EventData

### ISSUE THREAD

**Issue by jorgst** [Azure/azure-event-hubs-dotnet#246]
## How to Reproduce
1. Create an EventData object to be sent
2. Try to set PartitionKey as documented: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-programming-guide#partition-key

## Actual Behavior
1. Not able to set PartitionKey

## Expected Behavior
1. Be able to set PartitionKey similar to functionality available in WindowsAzure.ServiceBus nuget package.

## Versions  
- OS platform and version: Windows 10 version 1709 16299.248
- .NET Version: .NET Core 2.0 and .NET Framework 4.6.2
- NuGet package version or commit ID: 2.0.0-preview

## Use case
We use this to prioritize how many workers/webjob instance should be run per tenant (these are long running jobs) to avoid that one tenant use all the processing power. We are open to change this to another approach as long as we are able to achieve the same thing. That is:
1) Tenant A starts 1000 jobs
2) Later tenant B starts 1 job
3) 10 instances are working in parallell on tenant A's 1000 jobs and 1 instance is processing tenant B's single job.

We solve this in Azure WebJob with the following attribute on the funciton:
[Singleton("{PartitionKey}")]

**Comment by serkantkaraca** [comment]
PartitionKey is not a property of EventData in this client. Please try providing the partition key during SendAsync() call.

Here is the API: https://github.com/Azure/azure-event-hubs-dotnet/blob/de3c3309280e83345ebd8549bbf22c604a0ada82/src/Microsoft.Azure.EventHubs/EventHubClient.cs#L344

**Comment by jorgst** [comment]
I can't believe I didn't see that. Anyway thanks, case closed.
