### ISSUE TITLE
EventProcessorHost - processors for some partitions stop processing

### ISSUE THREAD

**Issue by stephenschwan** [Azure/azure-event-hubs-dotnet#254]
## Actual Behavior
1. Processors stop processing some partitions

We have been trying to track this down, but there are no exceptions etc.. or telemetry stating there might be an issue.  A restart of the web job fixes the issue until it happens again.  What can we do from a telemetry standpoint to try to track this - what should we be logging?

## Expected Behavior
1.  Exception or telemetry to state issue with check pointing or receiving events

## Versions  
- OS platform and version: Azure Web Apps - web job
- .NET Version: netcore 2
- NuGet package version or commit ID: 1.1

**Comment by serkantkaraca** [comment]
Are you on the latest client? Client 2.0.0?

**Comment by stephenschwan** [comment]
I am planning on doing a production deployment today with 2.0.  I will monitor it with the new nuget and see if this addresses it.

**Comment by serkantkaraca** [comment]
Any updates?

**Comment by stephenschwan** [comment]
So far so good.  If we can go two weeks without an issue it may be resolved.

**Comment by serkantkaraca** [comment]
Greak. I will ping you again 2 weeks later.

**Comment by serkantkaraca** [comment]
Any updates? Can we call it resolved?

**Comment by stephenschwan** [comment]
It seems this has been resolved with the 2.0 upgrade.  We haven't seen any processors stuck since.  We did run into another issue though - which i will create a new bug for.

thanks.

**Comment by stephenschwan** [comment]
Ok - We just had this happen again today.  We have no telemetry as to the reason - no exceptions, nothing.  Where should we start looking to track down the issue - or where should i start adding helpful telemetry....

**Comment by serkantkaraca** [comment]
Great you were able to reproduce the issue. Let's start with below.

* So how long did it run fine until you spotted the issue today?
* How many partitions are consumed in total and how many got stuck currently?
* I assume it doesn't recover on its own. Can you confirm this?
* Can you identify which partition(s) is stuck?
* Can you get a snapshot of all leases in the storage?
*  How many hosts do you run?
* Are you running with default options or custom options? What custom options do you have if any?

**Comment by stephenschwan** [comment]
Followed up internally for now.
