### ISSUE TITLE
Migrate from Microsoft.Azure.ServiceBus.EventProcessorHost for .NET framework

### ISSUE THREAD

**Issue by fmcharl** [Azure/azure-event-hubs-dotnet#258]
Hi,

I am trying to reach an expert to answer [this question](https://stackoverflow.com/questions/49285997/should-we-use-the-microsoft-azure-eventhubs-processor-library-with-net-framewor) I asked on stack-overflow.
Perhaps @serkantkaraca or @SreeramGarlapati could give a definitive answer.

Thanks for your time,

**Comment by serkantkaraca** [comment]
If you are just starting the development I would absolutely say use the new client. For existing products on ServiceBus client it is really up to customer at this point to decide whether to migrate or not. There are couple obvious advantages with new client over old such as new client is slimmer, it is open source, supports more platforms etc.

Please let me know if you have any questions.

**Comment by fmcharl** [comment]
Thank you both @jtaubensee and @serkantkaraca for answering quickly here and on StackOverflow, much appreciated.
We will then certainly upgrade to the new library.

**Comment by serkantkaraca** [comment]
Closing the thread. Please let us know if you hit any issues or have any questions.
