### ISSUE TITLE
EventProcessorHost - Event processors not being registered after switching to "Premium Performance" storage account

### ISSUE THREAD

**Issue by tobiasb** [Azure/azure-event-hubs-dotnet#260]
## Actual Behavior
1. Event processors not being registered

## Expected Behavior
1. Event processors are registered

We are using the `EventProcessorHost` to process messages from an EventHub. The event processor host requires a storage account for the coordination of event processors. After changing the storage account to use I'm having an issue where the event processors are not being registered anymore.

I verified it is a storage account related issue by creating another storage account with different configuration and it works. With the "bad" storage account, the `EventProcessorHost.RegisterEventProcessorFactoryAsync` is called successfully, yet the factory's `CreateEventProcessor` is never called. No exception is being thrown.

The only difference I could find between the "good" and the "bad" storage account is that the "bad" one is on a "Premium" performance plan whereas the "good" one is on a "Standard" performance plan.

There is evidence that the connection to the storage account is successful in principle because I can see that the blob container with the name of the event hub being created in the storage account.

## Versions  
- OS platform and version: Windows 10/Windows Server 2016 (Azure VM)
- .NET Version: 4.6.1
- NuGet package version or commit ID: 
WindowsAzure.ServiceBus 4.1.8
WindowsAzure.Storage 9.1.0

**Comment by serkantkaraca** [comment]
You are on .NET client as I understand. Can you file the issue here https://github.com/azure/azure-event-hubs/issues ? This repository is for .NET Standard library.

**Comment by tobiasb** [comment]
I'm using the .NET library, yes. It looks like https://github.com/Azure/azure-event-hubs points to this repository for .NET in general, do you still want me to create an issue there?

**Comment by serkantkaraca** [comment]
Yes please, move the issue there. This is the repository for https://www.nuget.org/packages/Microsoft.Azure.EventHubs/ i.e. different code base.
