### ISSUE TITLE
EventHubClient.SendAsync takes IEnumerable<EventData> while EventDataBatch makes ToEnumerable internal

### ISSUE THREAD

**Issue by shuxianc** [Azure/azure-event-hubs-dotnet#265]
## Actual Behavior
1. If we want to send an EventDataBatch with a specified partition key, we will call:  SendAsync(IEnumerable<EventData>, string);

2. However EventDataBatch has changed ToEnumerable() from public to internal, so we cannot  directly convert EventDataBatch to IEnumerable<EventData>.

## Expected Behavior
1. Change the signature from:
SendAsync(IEnumerable<EventData>, string);
to:
SendAsync(EventDataBatch, string);
2. SDK can  now call ToEnumerable() internally if we want to keep it as internal method.

## Versions  
- OS platform and version:
- .NET Version: .NET standard 2.0.0
- NuGet package version or commit ID: 2.0.0

**Comment by serkantkaraca** [comment]
You should set the partition key on EventDataBatch and then call SendAsync(EventDataBatch eventDataBatch).

Partition key is used in batch size calculation and key is stamped on the batch. You should not need to provide same partition key on the Send API again.

Let me know if you have any questios.

**Comment by shuxianc** [comment]
@serkantkaraca Thanks for the information! So if I don't explicitly set the partition key for EventDataBatch, is it still guaranteed this EventDataBatch will always land in a fixed partition? For example is it possible that upon built-in retry, SDK will send the EventDataBatch to a different partition than the first attempt. As a result the same EventDataBatch ends up in two different partitions?

**Comment by serkantkaraca** [comment]
Same partition key sends will always land on same partition, this is guaranteed.

**Comment by shuxianc** [comment]
@serkantkaraca Thanks! Just to double confirm, Is it still guaranteed even if I didn't specify partition key when creating EventDataBatch?

**Comment by serkantkaraca** [comment]
I might have got your question wrong. Guarantee is about partition key sends. If no partition key is involved then each individual send will land on a random partition.

**Comment by shuxianc** [comment]
I am referring to one single individual send of EventDataBatch, with no partition key involved. 
Is it possible that upon built-in retry of SDK, this single EventDataBatch will be sent to a different partition than the first attempt.  As a result the same EventDataBatch ends up in two different partitions?

**Comment by serkantkaraca** [comment]
Event Hubs doesn't provide exactly once delivery guarantee but provides at least once. Since there is no transaction, single successful send can end up 2 copies of the same message due to internal retries.

**Comment by shuxianc** [comment]
So if I want to ensure the same message always land in the same partition even in the case of internal retries, I should **specify partition key explicitly** for the EventDataBatch in its constructor. Is that correct?

**Comment by serkantkaraca** [comment]
You have 2 options:
* Either use partition key
* or use partition sender.

**Comment by shuxianc** [comment]
Thanks! That answers all my questions.

**Comment by serkantkaraca** [comment]
Closing the ticket. Let us know if you hot any issues.
