### ISSUE TITLE
Event Hub Thread Safety 

### ISSUE THREAD

**Issue by ryanLeenay** [Azure/azure-event-hubs-dotnet#269]
## Actual Behavior
1.  When running multithreaded application that sends event data to single event hub client every request receives a timeout exception due to lower exceptions in AMPQ dependency. See attached file for stack trace even if configurable timeouts are increased or disabled. If attempted thoughput is significantly reduced then errors only appear rarely.
2. However when running in release mode all timeout exceptions are not thrown and program completes with high thoughput normally. 

## Expected Behavior
1.  When running in debug or release a multithreaded eventhubclient.SendAsync should behave the same way escpecially if configurable timouts are disabled.

## Versions  
- OS platform and version: Windows 10, 1703
- .NET Version : .Net Standard  (additional detail) dependency of .Net Standard project witch is a dependency on .Net Core console app, 
- NuGet package version or commit ID: version 2.0.0

stack trace for all sendAsyc calls while in debug 
[errors.txt](https://github.com/Azure/azure-event-hubs-dotnet/files/1962143/errors.txt)

Repo steps:
0. Create Eventhub entity with only default consumer. 
1. Create eventhubClient object using EventHubClient.CreateFromConnectionString(<SharedAccessKey>) for particular entity path. 
1.1. Set eventhubClient transport type to Ampq or leave as default.
2. Use task list to start up at least 500 to 5000 sendAsyc() calls with a  Task.WhenAll. 
3. Run in debug mode and observe timeout exceptions for every request.
4. Publish build and run console app with dotnet, obsvere no exceptions.

**Comment by serkantkaraca** [comment]
Can you provide more details please? Repro steps as well if possible.

**Comment by ryanLeenay** [comment]
yes yes accidently hit enter providing info now

**Comment by ryanLeenay** [comment]
Important issue appears resolved when setting transport type to ampq.Websockets. Exploring

**Comment by serkantkaraca** [comment]
Thanks for the details. I will work on the given repro and update the thread.

**Comment by serkantkaraca** [comment]
Trying to reproduce the failures but not successful so far. I am using below code snippet for sending. All I observe is ServerBusy as first chance exception, not time outs.

            var client = EventHubClient.CreateFromConnectionString("connection string with ehpath");
            while (true)
            {
                var tasks = new List<Task>();
                for (int i = 0; i < 10000; i++)
                {
                    tasks.Add(client.SendAsync(new EventData(new byte[1000])));
                }

                Task.WhenAll(tasks).Wait();
                Console.WriteLine($"{DateTime.Now} Sent {tasks.Count} events.");
            }

**Comment by serkantkaraca** [comment]
Closing due to no response. Please reactivate if you want to continue on this thread.
