### ISSUE TITLE
Feature request: MessageSizeExceededException should contain information on events which are too large

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-event-hubs-dotnet#277]
I have a system where callers can send batches of data, which get sent to EventHub using the SendAsync that accepts an IEnumerable<EventData>. When a user sends too much data, a MessageSizeExceededException is thrown, but this exception does not contain any way to correlate back to the individual EventData(s) that were too big. 

The code uses the IEnumerable (i.e., the data flows from the caller into EventHub as an enumerable to improve performance), so I can't even inspect the passed in EventData, as by the time the exception occurs, the enumerable has already been enumerated. 

What would be perfect is if the exception contained the EventData(s) that were too large, or at least some information that allows a correlation. At the moment, I have to return "one of your messages were too large", which makes it harder to debug.

**Comment by serkantkaraca** [comment]
Why don't you use EventDataBatch? Its sole purpose is to address the issue you are pointing now.

**Comment by erick-thompson** [comment]
Doesn't EventDataBatch limit the total size of all EventData, as opposed to the size of each individual EventData? Looking at the code, it seems like it doesn't provide for checking an individual EventData for the 256kb limit.

**Comment by erick-thompson** [comment]
Thanks, I ended up getting the code from EventDataBatch (open source FTW) to tide me over until it's available from the SDK.

**Comment by serkantkaraca** [comment]
Closing

**Comment by serkantkaraca** [comment]
Closing

**Comment by serkantkaraca** [comment]
Closing since this feature request is already tracked by https://github.com/Azure/azure-event-hubs-dotnet/issues/236

**Comment by erick-thompson** [comment]
I'll put the details (what isn't is 236) into 236.
