### ISSUE TITLE
Reprocess failed messages - recommended pattern?

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-event-hubs-dotnet#278]
## Actual Behavior
1. `IEventProcessor.ProcessEventsAsync` throws an exception (perhaps due to bad message)
2. `ProcessEventsAsync` is called again, with even newer messages on that same partition.

Suppose in partition A we have events 1 through 4 all corresponding to the same business entity (and therefore should be processed in order). For simplicity assume all events are in their own batches and therefore get their own invocations of `ProcessEventsAsync`.

Event 1 is processed. _Checkpoint._
Event 2 throws an exception.
Event 3 throws an exception.
Event 4 is processed.  _Checkpoint._

Now for whenever the host process restarts, the checkpoint is past event 2 and 3 and therefore they will never be reprocessed. This is maybe fine if each event expresses the current state but is not appropriate if each event is has some important information in it.

## Expected Behavior

I would expected the host to attempt to enforce messages being processed in order with respect to a partition. 

Is there a way to achieve this with this package? I have considered just killing the process `IEventProcessor.ProcessErrorAsync` but this seems to heavy of a hammer since other partitions handled by the process might be fine.

This seems like a pattern people would commonly care about... what's the recommendation?

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.6.1
- NuGet package version or commit ID: NuGet package version 2.0.1

**Comment by serkantkaraca** [comment]
EPH doesn't allow reprocessing of the same batch of messages. You have full control on retrying process of failing message and there is not benefit at asking EPH to hand over the same set of messages where some of them are already processed.

If you still want to better control on the partition stream, you can implement your client by using low level Receive API. There, you can resume reading from any offset or sequence number.

**Comment by joelverhagen** [comment]
> You have full control on retrying process of failing message and there is no benefit at asking EPH to hand over the same set of messages where some of them are already processed.

I see, so from the standpoint of the EPH, the messages are processed in a "fire and forget" way: they are passed to `ProcessEventsAsync` and EPH assumes that they should never be passed again, no matter the error cases (unless of course the host is stopped explicitly or with a process termination and no `CheckpointAsync` was called). From face value, it seemed like EPH was meant to be a general purpose interface for processing event hubs and so I was thinking that not so many assumptions should be made -- but that is my personal opinion 😄.

Thanks for the clarification! I will drop down to the lower level API. I like the checkpoint persistence and leasing logic so I will try to use it piecemeal.

**Comment by serkantkaraca** [comment]
I think you can easily see these points regarding retry:

1. There is no difference between host retrying and your own retry implementation. Please note that EPH won't punish you because of retrying on the same message for days.

2. 'Bad message' will keep failing w/o changing the way you handle it. There might be intermittent issues while processing a message, say IO failures. Your own retry can handle such cases. Other than that, attempting to reprocess the same message even on other hosts should fail the same way.
