### ISSUE TITLE
EventData SystemProperties does not support unit testing code consuming it

### ISSUE THREAD

**Issue by Scythen** [Azure/azure-event-hubs-dotnet#280]
## Actual Behavior
1. EventData.SystemProperties is internal and can not be mocked or populated to test code consuming EventData

## Expected Behavior
1. A way to construct EventData with hydrated SystemProperties that can be used to test.

## Versions  
- NuGet package version: Microsoft.Azure.EventHubs 2.0.0

**Comment by Scythen** [comment]
A workaround is to use reflection to set the internal property.

**Comment by serkantkaraca** [comment]
For now please set SystemProperties by reflection. We will start working addressing testability issues soon.

**Comment by serkantkaraca** [comment]
Mockable library issue is tracked by https://github.com/Azure/azure-event-hubs-dotnet/issues/24
