### ISSUE TITLE
EPH unstable after when more instances on the dancefloor

### ISSUE THREAD

**Issue by jrouaix** [Azure/azure-event-hubs-dotnet#288]
## Actual Behavior
1. Hub with 32 partitions
2. One EPH instance, consuming all partitions ok
3. Here comes a new challenger : the 2nd instance start assigning partitions from 0 to 15, while the 1st instance has some lease lost.
4. Then we add a third instance : and then the instances are stealing lease and exchanging partitions endlessly. After several minutes, the balancing is still unstable.

## Expected Behavior
1. When more EPH instance comes, the transition to some other partitions distribution should be smooth and then stable.

## Versions  
- OS platform and version: Azure AKS. Containers base images are microsoft/dotnet:2.0-runtime
- .NET Version: .net core 2.0
- NuGet package version or commit ID: Microsoft.Azure.EventHubs 2.0.0 & Microsoft.Azure.EventHubs.Processor 2.0.1

**Comment by jrouaix** [comment]
And we could also reproduce the same problem with only 2 instances.

10:39:03 : pod1 initialized partitions 0 to 31
10:57:42 : pod 2 start
10:57:45 to 11:00:24 : pod 2 initialized partitions 0 to 15 while pod 1 lease lost -> expected behavior

11:03:51 : pod 2 initialized partitions 25 to 35, don't know why => pod 1 : New receiver with higher epoch of 'XXXX' is created
11:04:02 : pod 2 initialized partitions 16 to 24, don't know why => pod 1 : New receiver with higher epoch of 'XXXX' is created 

11:05:24 : pod 1 Exception while 'Checking Leases' on partition N/A
11:05:24 : pod 1 initialized partition 0 => pod 2 : New receiver with higher epoch of 'XXXX' is created
11:05:24 : pod 1 Partition 16 to 24 ::: close (reason : Shutdown)

11:06:36-09:13: pod 1 initialized partitions 0 to 15 => pod 2 : partions closed (lease lost), New receiver with higher exceptions ...

11:09:13 : pod 1 initialized partitions 16 to 31 => pod 2 : partions closed (lease lost), New receiver with higher exceptions ...

11:11:58 : pod 2 initialized partition 0 => pod 1 ... as usual


AND SO ON !

**Comment by serkantkaraca** [comment]
We have made some improvements to reduce partition moves recently. These improvements will be part of 2.1 client which we are working on the release today. I will let you know once the client is out then let's see if you observe any improvements.

**Comment by serkantkaraca** [comment]
2.1 released

**Comment by jrouaix** [comment]
Thanks, will test soon.
