### ISSUE TITLE
Consider using GitVersion

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#29]
https://github.com/GitTools/GitVersion.
Doco: http://gitversion.readthedocs.io/en/latest/

**Comment by serkantkaraca** [comment]
The versioning is managed by us for now Sean. I don't think our versioning requirements are that complex to plugin GitVerion. Afterall, it is 2 poject.json files to update.

**Comment by SeanFeldman** [comment]
Not a problem.
GitVersion helps to remove the manual aspect, so that versioning is based
on commits. If it doesn't bring a value, then it's not needed.


Kind regards,
Sean Feldman
