### ISSUE TITLE
SAS token expiration management

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-event-hubs-dotnet#291]
More a question than an issue: does one need to renew the SAS token used to create `EventHubClient` when it expires, and if so, how is it done?

For context, we use
```
EventHubClient.CreateFromConnectionString($"Endpoint={eventHubSchemeAndServer};EntityPath={eventHubPath};SharedAccessSignature={eventHubCreds.SharedAccessSignatureToken};OperationTimeout={Settings.EventHubTimeout}")
```
with SAS tokens that expire every 12h to receive messages from Event Hubs.

I was looking for something like `StorageCredentials.UpdateSASToken(...)` used in the Azure Storage Nuget package but I do not see that on EventHub.

**Comment by serkantkaraca** [comment]
Token is auto renewed when it gets expired. You don't need to create a new client.

**Comment by mmaitre314** [comment]
Reopening as token-renewal does not seem to be working: my code started crashing with `System.UnauthorizedAccessException Put token failed. status-code: 401, status-description: ExpiredToken: .` from

```
Microsoft.Azure.EventHubs Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver+<OnReceiveAsync>d__13.MoveNext
Microsoft.Azure.EventHubs Microsoft.Azure.EventHubs.PartitionReceiver+<ReceiveAsync>d__31.MoveNext
```

Is `ReceiveAsync()` supposed to replace the original SAS token by a new SAS token from the server?

**Comment by serkantkaraca** [comment]
Your client is providing an already expired token to the service. Can you check whether you client is running with wrong system clock?

**Comment by mmaitre314** [comment]
The tokens are issued with 12h validity so it is unlikely that the system clock is that off. What I am missing is how `EventHubClient` can auto-renew SAS tokens when they expire. Let's say I create `EventHubClient` with a 12h token and then 13h later I call `EventHubClient.CreateEpochReceiver()`. At that point the SAS token is not valid anymore. How does `EventHubClient` get a new valid token based on an expired token? Should I create all the receivers right at the beginning and never close them? Right now I recreate them when `PartitionReceiver.ReceiveAsync()` throws an unknown exception, to try to recover the connection, but I am not sure that's the correct way to handle such exceptions.

**Comment by serkantkaraca** [comment]
Service closes the link on UnAuth case. When client retries it attempts to reopen the link and opening a link requires authN flow. At this point how client regenerates a new token.

This is the token handler on the client. 
https://github.com/Azure/azure-event-hubs-dotnet/blob/441b0b492bd87f3f194b14ec90166786f3caeee7/src/Microsoft.Azure.EventHubs/Amqp/AmqpEventHubClient.cs#L278

Are you able to reproduce the failure in a shorter duration than 12 hours? We have stress tests running for weeks and they never need to recreate the senders or the receivers. There is something special in your case apparently.

**Comment by mmaitre314** [comment]
I switched to not-recreating the receivers and so far things are looking good. I'll keep on monitoring but that was likely the problem.
