### ISSUE TITLE
Enable fetching information on consumer groups through the client

### ISSUE THREAD

**Issue by avodovnik** [Azure/azure-event-hubs-dotnet#292]
Currently, the client doesn't seem to enable fetching any information about consumer groups (including the default consumer group), like the "old" client did. I would like to be able to call `client.GetConsumerGroupInformationAsync()` for example, in a similar fashion to `client.GetRuntimeInformationAsync()`. I tried adding this myself, but I haven't seen any reference to an endpoint letting me do this through AMQP in the documentation.

**Comment by serkantkaraca** [comment]
Consumer group information or settings are on the other SDK classes like EventHubClient or PartitionReceiver. Let me know if you cannot find the setting or data that you are looking for.

**Comment by avodovnik** [comment]
@serkantkaraca hm... they're not in `EventHubRuntimeInformation` (where I'd expect them) or `EventHubPartitionRuntimeInformation`. They're also not on EventHubClient - that's what I'm saying is missing. To clarify, I'm looking for an alternative to [this REST call](https://docs.microsoft.com/en-us/rest/api/eventhub/consumergroups/listbyeventhub), but it doesn't seem to be provided in this SDK. Am I missing something obvious?

**Comment by serkantkaraca** [comment]
I see. You are looking for GetConsumerGroups API on NamespaceManager. https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.getconsumergroups?view=azure-dotnet

Management operations are not supported on this client yet. It will happen this year though. In the meantime you can use EH management client: https://www.nuget.org/packages/Microsoft.Azure.Management.EventHub/

**Comment by serkantkaraca** [comment]
Closing for now. Please let me know if you have any other questions.
