### ISSUE TITLE
EventProcessorHost.cs is missing constructor with 4 arguments

### ISSUE THREAD

**Issue by alancast** [Azure/azure-event-hubs-dotnet#294]
## Rundown
EventProcessorHost has a constructor that takes in 4 arguments (documented [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventprocessorhost.-ctor?view=azure-dotnet#Microsoft_ServiceBus_Messaging_EventProcessorHost__ctor_System_String_System_String_System_String_System_String_)) but that is not reflected in the nuget package. The EventProcessorHost.cs file is just missing that constructor.

## Actual Behavior
1. `error CS1729: 'EventProcessorHost' does not contain a constructor that takes 4 arguments`

## Expected Behavior
1. No error

## Versions  
- OS platform and version: macOS 10.13.5
- .NET Version: netcoreapp2.0
- NuGet package version or commit ID: 2.1.0

**Comment by serkantkaraca** [comment]
You are looking at Microsoft.ServiceBus.Messaging documentation. This is Microsoft.Azure.EventHubs SDK.

**Comment by alancast** [comment]
Just realized that :-(. Apologies for the false issue. 

In case anyone else runs into this: 
The online documentation for this repo is [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessorhost.-ctor?view=azure-dotnet)
