### ISSUE TITLE
Closing the receiver can allow OnChangeRoleAsync while ReceivePumpAsync is running

### ISSUE THREAD

**Issue by JohnLTaylor** [Azure/azure-event-hubs-dotnet#295]
## Preconditions
An AmqpPartitionReceiver is processing a large number of batches from an EventHub

## Actual Behavior
1. Service Fabric calls OnCloseAsync()
  a. AmqpPartitionReceiver's OnCloseAsync() is closed
3. Service Fabric calls OnChangeRoleAsync()
4. AmqpPartitionReceiver's OnReceiveAsync is still active
5. A FabricNotPrimaryException exception is thrown

## Expected Behavior
1. Service Fabric calls OnCloseAsync()
  a. AmqpPartitionReceiver's OnCloseAsync() is closed
    i.  AmqpPartitionReceiver's OnReceiveAsync is still active
    ii. AmqpPartitionReceiver's OnReceiveAsync finishes gracefully
2. Service Fabric calls OnChangeRoleAsync()

## Versions  
- OS platform and version: WindowsServer 2016-Datacenter
- .NET Version: .NetCore 2.1
- NuGet package version or commit ID: v2.1.0

**Comment by serkantkaraca** [comment]
Thx for the fix. I have merged it now.
