### ISSUE TITLE
Lease and Offset should be readable from PartitionContext

### ISSUE THREAD

**Issue by maulik13** [Azure/azure-event-hubs-dotnet#303]
PartitionContext does not allow reading Lease and Offset

In the EventProcessorHost under ServiceBus namespace, Lease was accessible from inside a partition processor and this allowed reading the current Offset from a partition. We use this in our log analytics and for measuring delays and performance while processing events. It would be very useful for us to be able to read these properties from PartitionContext.

**Comment by serkantkaraca** [comment]
Created a PR https://github.com/Azure/azure-event-hubs-dotnet/pull/304

**Comment by maulik13** [comment]
Thank you :)
