### ISSUE TITLE
Connection String builder for IoT Hub does not respect High Availability guidance from IoT Hub

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-event-hubs-dotnet#305]
## Actual Behavior
1. In order to use this library to connect to IoT Hub, we need to provide the EventHub-compatible connection string, in this format (see this issue: https://github.com/Azure/azure-event-hubs-dotnet/issues/185)
`Endpoint=sb://MYIOTHUB.servicebus.windows.net;SharedAccessKeyName=iothubowner;SharedAccessKey=-secret removed-`

Using the native IoT Hub connection string makes the library fail with the following error:
`Illegal connection string parameter name 'HostName' Parameter name: connectionString`

However, using the EH-compatible connection string goes against the MSFT recommendations for making sure your endpoint can connect to the IoT Hub service when a disaster forces Microsoft to fail over IoT Hub to another region. From the docs (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-ha-dr):

_The Event Hub-compatible name and endpoint of the IoT Hub built-in Events endpoint change after failover. When receiving telemetry messages from the built-in endpoint using either the event hub client or event processor host, you should use the IoT hub connection string to establish the connection. This ensures that your back-end applications continue to work without requiring manual intervention post failover. If you use the Event Hub-compatible name and endpoint in your back-end application directly, you will need to reconfigure your application by fetching the new Event Hub-compatible name and endpoint after failover to continue operations._

## Expected Behavior
1.  The Event Hub .NET Standard library is able to work with the native IoT Hub connection string and its access policies.

## Versions  
- OS platform and version: Docker
- .NET Version: Core 2.1
- NuGet package version or commit ID: 2.1.0

**Comment by serkantkaraca** [comment]
This is a known missing feature compared to .Net SDK. You can track the original issue here https://github.com/Azure/azure-event-hubs-dotnet/issues/167

**Comment by murdockcrc** [comment]
@serkantkaraca: that is correct. Just want to point out that under the current circumstances, it is not possible to use the event hubs library **and** be compliant with Microsoft's own recommendation to properly deal with a regional disaster of an iot hub service. The chances of such an event happening are very low but its impact very high, so I'd appreciate if the dev team would prioritize the resolution of the referenced GitHub issue. Thx

**Comment by serkantkaraca** [comment]
Let's track this at #167
