### ISSUE TITLE
Spikes in event hub response time

### ISSUE THREAD

**Issue by ChrisJr** [Azure/azure-event-hubs-dotnet#316]
## Actual Behavior
1. I have an Azure functions pushing events to the event hub. I use EventHubClient.CreateFromConnectionString(connection string) to create the connection and reuse the same connection. The solution works, but there are spikes in response time that go up to 10 seconds(even more, but at this point I added code that timeouts after 10s) as opposed to normal reponse time that ranges between 20-100ms. This behaviour seems to be quite consistent with the spikes occuring at regular intervals.

## Versions  
- OS platform and version:
- .NET Version: netstandard2.0
- NuGet package version or commit ID: Microsoft.Azure.EventHubs version 2.1.0,

**Comment by serkantkaraca** [comment]
What is your typical throughput? Connects can be aborted after some certain idle time. When this happens, the following send attempt will spend some substantial time to create new SSL channel which might look like latency spikes.

**Comment by ChrisJr** [comment]
It's not that high atm, and varies a lot, but it's still several messages per second. Looking at the graphs I can see that each individual event hub gets hit at least once every few seconds. I had the same initial tought as you, but I don't think the connection should abort after so little time. 

I am not that familiar with how event hub works, but currently my guess it that those spikes are because multiple messages are attempting to use the same connection. My inital code to reuse the connection is very rudimentary and simple, so now I am looking into using object pooling and having multiple connections available.

**Comment by serkantkaraca** [comment]
Have you also checked client side resources such as CPU, available memory and number of threads? See if GC is kicking in during the spikes. Try running tcp ping along with your client and see if the network latency is increasing or not. This might be a service side issue as well but hard to tell w/o enough pointers.

**Comment by ChrisJr** [comment]
Really appreciate the help. The function app is on a dedicated plan, and resource consumption is not an issue as far as I can tell. I got pulled on other things, but as soon as I have some time I will try to implement pooling and see how that works out. Currently the latency spikes are not affecting functionality, and I have timeout code that aborts and retries so nothing gets lost, but i do want to fix this issue. Would it be possible that ,my guess is correct or would it be a waste of time?

**Comment by serkantkaraca** [comment]
High latency is always hard to root cause. Can you try running a dummy client to receive from a new consumer group? If this is a service issue then you will observe latency spikes at the same time as the service, if this is a client issue you will observe spikes but at different times. If this is networking issue then your test client might not observe any spikes at all.

**Comment by serkantkaraca** [comment]
Yes, let's keep it open. Regarding the dummy client I recommend, you need to do send instead of receive. You can create a test EH with the same number of partitions as the production. Btw, are you doing client sends or partition sends?

**Comment by serkantkaraca** [comment]
Please reactivate if you have more data to share.

**Comment by MaximKojineMojio** [comment]
@ChrisJr I am wondering if this issue is resolved or you still experience it? 
Thanks

**Comment by ChrisJr** [comment]
@MaximKojine I am still experiencing spikes although at a lower rate since I implemented connection pooling. The traffic was also increased significantly since then but it has not affected the rate of the spikes so we just left it as is since it would be too much trouble to troubleshoot something that is not affecting us that much.
I am still interested in a solution(more out of curiousity), so we can continue the dialog here.

**Comment by serkantkaraca** [comment]
How often do you see 10-sec latency spikes?

**Comment by MaximKojineMojio** [comment]
@ChrisJr  Thank you for your response. We experience similar spikes, and we try to resolve them.
And I have a few questions: Do you see these spikes in Azure Portal Metrics for this EvenHub? Or you experience them only on the client side? Did you capture ETW with PerfView for send operation? 
We don't see these spikes in the Portal, but our logging logic (wrapper around, SendAsync) captures 6-8 secs spikes. 
Seems like it could be reproduced by using a console app which sends messages to EvenHub from multiple (hundred) threads.

**Comment by serkantkaraca** [comment]
Can you ping the servicebus host name with your namespace and tell me service host name which should look like 'ns-sb2-prod-am3-001.cloudapp.net'? I will check whether anything going on the service side.

**Comment by Gemakk** [comment]
> Can you ping the servicebus host name with your namespace and tell me service host name which should look like 'ns-sb2-prod-am3-001.cloudapp.net'? I will check whether anything going on the service side.

`ns-eh2-prod-dm2-509.cloudapp.net` is the URL.  However, we already had PG engineers look at various namespaces, which all appeared 'fine' from the server-side.  Since we can reproduce this issue for any namespace, we're investigating potential Client-side issues.

**Comment by serkantkaraca** [comment]
Are you able to test a standalone and monitor the latencies? If standalone client findings correlate to Azure Functions results then that can help to point to a service side issue.

**Comment by timpel** [comment]
Using a simple console app that sends data to the EventHub via TPL, we're seeing spikes in calls to EventHubClient.SendAsync(EventData, partitionKey) in the range of 1-3 seconds (up to 7s occasionally) when queuing up a large number of messages. When present, the delays usually impact 0.5-1% of calls, so we are trying to investigate whether there are issues in the interaction between TPL and the EventHub Client.

**Comment by serkantkaraca** [comment]
Can you try 2 things with your console app and see if you still see similar high latencies?

- Send w/o partition key.
- Run with full .Net client  - https://www.nuget.org/packages/WindowsAzure.ServiceBus

**Comment by timpel** [comment]
Thanks - we still see similar latencies with no partition key, and when using .NET 4.6.2 + ServiceBus.

**Comment by MaximKojineMojio** [comment]
We converted the app to .NET 4.6.2 and replaced EventHubClient with WindowsAzureServiceBus.
Yes, we saw spikes as well. But we also see patterns, which we didn't see with EventHub Client. The number of spikes somehow proportional to MaxDegreeOfParallelism.
Three more tests:
The same app with "Task.Delay(100)" instead of "eventHubClient.SendAsync()" - no spikes.
The same app with "httpClient.GetAsync('www.google.com')" instead of "eventHubClient.SendAsync()" - no spikes.
The same app with EventHubClient pool - has the same spikes as the app with one EventHubClient

**Comment by MaximKojineMojio** [comment]
@ChrisJr - Sorry for hijacking this issue.

**Comment by ChrisJr** [comment]
No worries. I already gave up on the issue, my interest in this being more out of curiosity. If you however come up with a solution/explanation I would be very interested. :)

**Comment by serkantkaraca** [comment]
Alright, latency doesn't seem to be on the client side regarding your findings. I would like to check your namespace but I cannot ask it here. If possible please open a support request and I can do some service side investigation. 2 more questions below.

- What is the maximum latency you are observing?
- Do you see an interval pattern such as latency makes spike every 60 seconds?

**Comment by Gemakk** [comment]
> I would like to check your namespace but I cannot ask it here. If possible please open a support request and I can do some service side investigation.

Hi Serkant, I see you were once part of an old ticket we had, so I'll just add you to our existing ticket 😄
