### ISSUE TITLE
A receiver with a higher epoch '' already exists.

### ISSUE THREAD

**Issue by grik001** [Azure/azure-event-hubs-dotnet#317]
Hi,

I have noticed I keep getting the below error when using Logic Apps to WorkFlowRuntime events to EventHub and listen on EventHub using Functions.

Is this a known issue or am I configuring something incorrectly? Is it possible that I am missing some messages due to this error?

EventProcessorHost error (Action=Open) : Microsoft.ServiceBus.Messaging.ReceiverDisconnectedException: A receiver with a higher epoch '636730203068015448' already exists. A new receiver with epoch 6499 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:c3d4ee49-eb97-4107-aa75-e8337d1a5602_B16

**Comment by serkantkaraca** [comment]
That epoch number is super high. Something must be running misconfigured. Make sure you don't have any external receivers on your partitions.

**Comment by serkantkaraca** [comment]
Please reactivate if you want to track the issue.
