### ISSUE TITLE
Azure Event Hub periodically generate 508 B message to Data Storages

### ISSUE THREAD

**Issue by edilyan** [Azure/azure-event-hubs-dotnet#321]
When I Capturing Azure Event Hub to any Data Storage (Azure Blob Storage or Azure Data Lake) it's starts too send 508 B header of message (empty message) every 5 minute. 
How can I solve this problem? because we want to use this mechanism for logging system, and it will interfere us.

**Comment by serkantkaraca** [comment]
This is not related to the client. Can you create the issue at https://github.com/Azure/azure-event-hubs?
