### ISSUE TITLE
Best practices for retrying when hitting throttling exceptions while sending batch

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-event-hubs-dotnet#325]
## Actual Behavior

I'm trying to use the [Polly](https://github.com/App-vNext/Polly) library to implement `WaitAndRetry` with an exponential backoff policy to mitigate a throttled Event Hub entity, by handling the `ServerBusyException`.

At first, directly retrying, the `EventHubClient.SendAsync(EventDataBatch)` call was failing deep inside the Amqp C# library with a message similar to:

    Unhandled Exception: System.TimeoutException: The operation did not complete within the allocated time 00:00:00.9641153 for object message

I then tried to keep each `EventData` message in a list, while adding them to the batch. Upon receiving the `ServerBusyException` I re-created the batch and re-added all the messages that had been kept in the list.

This seemed to improve my chances of success.

However, after a while I still get the dreaded `System.TimeoutException` frequently from the Amqp C# library.

What is the official way to deal with a throttled entity while sending a batch ?

## Expected Behavior
1. Be able to retry sending a batch without re-creating the batch from cached `EventData` instances.
2. 

## Versions  
- OS platform and version: Windows 10
- .NET Version: Net Standard 2.0
- NuGet package version or commit ID: 2.1.0

**Comment by springcomp** [comment]
No the issue is persistent. This makes sense, though.
When sent, a message might have been read or disposed.
That's why I got around it by keeping the messages internally and recreating the batch each time I buy a throttled request.

**Comment by serkantkaraca** [comment]
Let me try to reproduce the issue. I will update the thread with my findings.

**Comment by serkantkaraca** [comment]
Re-sending the same batch is working in my case. I even pushed the client to hit ServerBusy and this still works. You are not using .Net SerbiceBus SDK, right? This SDK allows sending the same message multiple times, same as the batch.
