### ISSUE TITLE
Unit test with real azure infrastructure 

### ISSUE THREAD

**Issue by davidrevoledo** [Azure/azure-event-hubs-dotnet#334]
## Actual Behavior
1. Currently to test this library a storage and a real hub is mandatory.

## Expected Behavior
1.  It'd be handy to abstract the test for real implementation, they are more integration test than unit test if we need to really hit azure infrastructure  for whole components.

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by davidrevoledo** [comment]
@serkantkaraca what do you think about it ?

**Comment by serkantkaraca** [comment]
We have another issue tracking testability concerns - https://github.com/Azure/azure-event-hubs-dotnet/issues/24

That would be great if you can contribute to that thread with your ideas.

**Comment by davidrevoledo** [comment]
@serkantkaraca Sure will find !
