### ISSUE TITLE
Multiple EventProcessor Running in a EventProcessorHost

### ISSUE THREAD

**Issue by davidrevoledo** [Azure/azure-event-hubs-dotnet#340]
I was answering a few question about eventhub behavior in the `netcore` slack `aspnetcore.slack.com`
mhe@amberkinetics.com was wondering how to run and stop a few processing with the same host as the method to register looks like the host support multiple processor at the same time.

However if you run 2 processors within the same host an error will be shown `A PartitionManager cannot be started multiple times.`  which make sense as the host is running  a partition manager.

``` C#
            var eventProcessorHost = new EventProcessorHost(
                EventHubName,
                PartitionReceiver.DefaultConsumerGroupName,
                EventHubConnectionString,
                StorageConnectionString,
                StorageContainerName);

            // Registers the Event Processor Host and starts receiving messages
            await eventProcessorHost.RegisterEventProcessorAsync<SimpleEventProcessor>();
            await eventProcessorHost.RegisterEventProcessorAsync<SimpleEventProcessor2>();
```

However if you unregister a host to stop the processor (this works) and you try to start and register other it throws same error.

![image](https://user-images.githubusercontent.com/8322252/47887704-a6e24800-de1f-11e8-935a-3e0c62548dfd.png)

Seems the problem is because when stopped the partition manager don't clean the task.
https://github.com/Azure/azure-event-hubs-dotnet/blob/4aaf7551b90de09cbb7097adb756efc842032cd6/src/Microsoft.Azure.EventHubs.Processor/PartitionManager.cs#L75

Is something that I missing here ? 

## Actual Behavior
1. If the host unregister the processor and start again it throws an exception

## Expected Behavior
1. The client should be able to stop and start the host with other processor or at least that the question.

## Versions  
- OS platform and version: Windows
- .NET Version: NetCore
- NuGet package version or commit ID: Last

**Comment by serkantkaraca** [comment]
Seems like a bug to me. Can you submit a fix? Basically nullify this.runTask when stop is called.

        public async Task StopAsync()
        {
            this.cancellationTokenSource.Cancel();
            var localRunTask = this.runTask;
            if (localRunTask != null)
            {
                await localRunTask.ConfigureAwait(false);
            }
        }

**Comment by davidrevoledo** [comment]
Yeah I though the same looking into the code but I wasn't sure if I was missing something I wasn't aware of.

Sure thing will test first with the same project to check if but it should work as it stop in the validation.
