### ISSUE TITLE
EventDataBatch has no way to access EventData elements

### ISSUE THREAD

**Issue by mikehe12** [Azure/azure-event-hubs-dotnet#355]
## Actual Behavior
1. EventDataBatch has no way to access EventData elements

## Expected Behavior
1. EventDataBatch should have a way to access EventData elements. This is present in WindowsAzure.ServiceBus, the older package for working with event hubs.

Is there a reason this functionality was removed? It breaks compatibility with existing code that used WindowsAzure.ServiceBus.

A common usage pattern is to save messages that couldn't be sent to be retried later. If an EventDataBatch is used, then the upload code cannot easily extract the data in failed batches to be saved for retrying. This then requires tight coupling between the code that adds EventData items to an EventDataBatch, and the code that tries to upload the EventDataBatch, if failed data is to be retrieved.

## Versions  
- OS platform and version: Any
- .NET Version: 4.7 and up
- NuGet package version or commit ID: 2.2.1

**Comment by serkantkaraca** [comment]
Thanks for pointing this. I have created a PR with the fix. https://github.com/Azure/azure-event-hubs-dotnet/pull/356
