### ISSUE TITLE
Update Azure Storage package to 9.4 which is split to multiple packages

### ISSUE THREAD

**Issue by darthkurak** [Azure/azure-event-hubs-dotnet#359]
Hi. Azure Storage sdk was split, in version 9.4, to multiple packages. It has significant updates (like using HttpClient and be thread safe). EventHub package use old one, so I can't use newest EventHub package and Azure.Storage in the same project.

**Comment by davidrevoledo** [comment]
@serkantkaraca is there a plan to migrate this ? It might be a breaking change.

**Comment by serkantkaraca** [comment]
https://github.com/Azure/azure-event-hubs-dotnet/pull/369

**Comment by ththiem** [comment]
Any update on this work? We're now also running into version conflicts between 9.3.3 referenced here and the latest 9.4.2 azure sdk.

**Comment by serkantkaraca** [comment]
Seems PR has been pending for a while now. I will try to get this merged ASAP. Please note that change is done for Net Standard and UWP builds only. Full dotNet lib doesn't support proxy so I cannot move that.

**Comment by serkantkaraca** [comment]
Merged to dev branch.
