### ISSUE TITLE
How to implement Event Hub health checks

### ISSUE THREAD

**Issue by Allsetra-RB** [Azure/azure-event-hubs-dotnet#361]
I was redirected here from an Azure support ticket.

I need help implementing health checks for our Event Hub connection for both client and server health.

Unfortunately we've been running into problems with our use of Event Hubs (5 major issues in the past 3 months) and we can't find out what is happening. The Azure portal shows no abnormal backlog, yet one of 32 round-robin filled partitions has a 100.000 message backlog while other partitions are completely up-to-date (500 message backlog, which is normal for our throughput). I do not know how to detect this in an Event Hub consuming application and even our assigned support engineer doesn't know how to detect this issue. We have also tried using the Service Bus Explorer, but our support engineer can't show us how to detect his issue there either. Our support engineer also pointed us to service bus performance counters, but they won't install properly so we can't use those either.

So: Would you be able to implement health checks in a sample project so we can apply and extend this in our application?

Things we must be able to detect are:
- Current backlog per partition
- Server communication lag (when the library talks to the server for filling its prefetch queue or marking checkpoints)
- Prefetch queue fill times

We've also seen some 'server errors' in the Azure portal metrics. How are these manifested in the consuming application? Are they handled completely by the library or are they (sometimes) thrown to the consumer application?

**Comment by serkantkaraca** [comment]
As I understand there was a misunderstanding about your issue. Azure Support is supposed to reach you out on this. I am closing the ticket since it is not directly related to client SDK.
