### ISSUE TITLE
Create Consumer Group with a Shared Access Signature (SAS)

### ISSUE THREAD

**Issue by simonness** [Azure/azure-event-hubs-dotnet#362]
I'd like to programmatically create a consumer group, effectively calling [this API method](https://docs.microsoft.com/en-us/rest/api/eventhub/create-consumer-group) using a SAS.

I'm aware of the more general management library https://github.com/Azure/azure-sdk-for-net, but it seems to need authentication via a Service Principal etc (the management client constructor takes a `ServiceClientCredentials`).  It doesn't look like it supports constructing a management client with a `TokenProvider` like for example the specific Service Bus Management Client does [here](https://github.com/Azure/azure-service-bus-dotnet/blob/25492708c73a0d1e07e73ef5ca02de0ff2b28b79/src/Microsoft.Azure.ServiceBus/Management/ManagementClient.cs#L39).

Is there a plan to support management functions in this library?  Or is there another library I might be missing that I can use to help achieve this?  Thanks!

**Comment by serkantkaraca** [comment]
This SDK doesn't support management operations yet but it is part of our 2019 plan. For now, I recommend implementing using HTTP calls to service REST end point. Let me know if you have any questions.

**Comment by simonness** [comment]
Thanks @serkantkaraca, that makes sense 👍
