### ISSUE TITLE
Problem with GetRuntimeInformationAsync().PartitionCount return allways 1

### ISSUE THREAD

**Issue by mendesbarreto** [Azure/azure-event-hubs-dotnet#364]
Hello guys, how it's going?

I am facing a problem with EventHubClient, it is giving me the wrong number of partitions.

## Actual Behavior

When I try to run the fallow code:

```C#
var runtimeInformation = await _eventHubClient.GetRuntimeInformationAsync();
var countPartion = runtimeInformation.PartitionCount; // 1
var partitionIds = runtimeInformation.PartitionIds; // Exists only one ID
``` 
The line ```runtimeInformation.PartitionCount``` returns allways 1 and I am sure I have 2 partitions on EventHub site.

## Expected Behavior
 ```runtimeInformation.PartitionCount``` should return 2;
 ``` runtimeInformation.PartitionIds``` should contains 2 ids;

## Versions  
- Windows 7 Professional 64 bits
- .NET Core 2.1
- NuGet package versio: 2.2.1

**Comment by mendesbarreto** [comment]
Hello @serkantkaraca.

I made a test with the follow settings:

* Windows 7 Professional 64 bits
* .NET Framework 4.6.1
* NuGet package versio: 2.2.1

The same result =( .

**Comment by serkantkaraca** [comment]
Sorry, I meant try with Azure.ServiceBus SDK.  https://www.nuget.org/packages/WindowsAzure.ServiceBus

**Comment by mendesbarreto** [comment]
ahhahahaha, no problem. I will try it!

**Comment by mendesbarreto** [comment]
I tested with service bus and the same problem happens. I really don't understand, because the default partitions size is 2, but I can't retrieve this information.

**Comment by serkantkaraca** [comment]
Can you also check it on the portal? And, how did you create the event hub?

**Comment by mendesbarreto** [comment]
Thank you so much,

I did not notice my company has the right to create a Event Hub with one partition. When I did the training the guy told me the default partition number was 2 and minimum was just 2 .

Sorry for the problem.
