### ISSUE TITLE
EventProcessorHost using custom Consumer Group not receiving any messages 

### ISSUE THREAD

**Issue by Strandfelt** [Azure/azure-event-hubs-dotnet#370]
I suspect that a breaking change has been deployed to the IoT Hub, making NuGet version 2.0.0 of the Microsoft.Azure.EventHubs.Processor fail to receive any messages when creating a custom consumer group in the IoT Hub.

I can't help noticing that a new version of the NuGet (3.0.0) was released yesterday. Could this mean that breaking changes have been introduced to the Event Hub endpoint in Azure IoT Hub at the same time?

## Actual Behavior
The following steps have been working until today, February 20, where they stopped working in an IoT Hub instance.
1. Create a message routing configuration in the IoT Hub that route Device Telemetry Messages to the events endpoint of the IoT Hub
2. Define a custom consumer in the IoT Hub
3. Initialize an EventProcessorHost with the following code in a project using NuGets `Microsoft.Azure.EventHubs` version 2.0.0 and `Microsoft.Azure.EventHubs.Processor` version 2.0.1:
```
  var consumerGroup = "eventprocessorhost";
  host = new Microsoft.Azure.EventHubs.Processor.EventProcessorHost(
                eventProcessorHostName,
                eventHubName,
                consumerGroup,
                eventHubConnectionString,
                storageConnectionString,
                storageContainerName);
```
4. Send D2C messages to the IoT Hub 
5. No messages are received in the EventProcessorHost 
6. Update NuGets `Microsoft.Azure.EventHubs` and `Microsoft.Azure.EventHubs.Processor` to version 2.2.1
7. Rebuild code and run
8. Messages are now received

## Expected Behavior
1. Code built on NuGet packages version 2.0.0 should continue working or information regarding breaking changes in the IoT Hub events endpoints should have been communicated

## Versions  
- OS platform and version: Tested on Windows 10 Pro and in AKS as Linux containers
- .NET Version: .NET Core 2.0
- NuGet package version or commit ID: `Microsoft.Azure.EventHubs` version 2.0.0 and `Microsoft.Azure.EventHubs.Processor` version 2.0.1

**Comment by serkantkaraca** [comment]
IOTHub doesn't employ this SDK. They have their own client implementation. 

Can you try receiving with 3.0.0? We have bunch of tests with processor host and we didn't come across any issues yet.

**Comment by Strandfelt** [comment]
Here, in the IoT Hub documentation, it states that the built-in endpoint in the IoT Hub is EventHub compatible: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-hub/iot-hub-devguide-messages-d2c.md#event-hubs

As stated, the issue was sorted out by upgrading to version 2.2.1 (I had problems pulling 3.0.0 earlier today, but it probably works as well), but I would like to know how the functionality using a release just less than 1 year old can stop working without notice.
If you believe that this is an issue with the IoT Hub rather than this SDK, please let me know whereto I should forward this issue.

**Comment by serkantkaraca** [comment]
When you receive directly from Event Hubs there is nothing there regarding the IOTHub at that moment. Your client is basically talking to Event Hubs endpoint, not IOTHub. Therefore, I believe we should downgrade the issue to Event Hubs only. I will try to get a simple repro shortly. I will provide the results here.

**Comment by serkantkaraca** [comment]
I am not able to repro with below packages. Are you able to repro the issue if you move back to V2.0.1?

![image](https://user-images.githubusercontent.com/16924470/53127856-4b47e180-3518-11e9-95b6-a34977d0a3b1.png)

**Comment by Strandfelt** [comment]
Hi,

I just tried downgrading to the specific versions, but I was not able to reproduce the issue. I guess you can close the issue for now.
However, it did stop our UAT environment from running on AKS and I was able to reproduce locally, prior to submitting the issue, so the uncertainty worries me a bit going forward. Maybe more of a hiccup in our IoT Hub instance rather than an issue with the packages.

**Comment by serkantkaraca** [comment]
Let me know if you find anything else. Closing the issue for now.
