### ISSUE TITLE
Need for System.Net.Http reference when targeting full framework?

### ISSUE THREAD

**Issue by kjohann** [Azure/azure-event-hubs-dotnet#374]
As you probably know, there are a lot of issues with the System.Net.Http NuGet package when used in projects targeting full framework (just google "System.Net.Http problems" and see all the frustration it causes). 

Is there any reason why the `PackageReference` for System.Net.Http isn't a conditional include? As far as I know, you shouldn't need it when targeting full framework starting from version 4.7, which means you could add another ItemGroup for target `net47` which has an `<Reference Include="System.Net.Http" />` instead of the `PackageReference`.

With the current dependencies of the Microsoft.Azure.EventHubs package, we get a whole bunch of binding redirects for System.Net.Http that redirects to version `4.2.0.0`. But we run full framework (4.7.1 to be exact), which means that we need to reference version `4.0.0.0`. We don't seem to get any runtime errors though, but we have some serious trust issues when it comes to System.Net.Http. We've spent countless hours tracking down "Could not load file or assembly" errors for System.Net.Http in the past.

**Comment by serkantkaraca** [comment]
Thanks for pointing. I am removing it now. https://github.com/Azure/azure-event-hubs-dotnet/pull/377
