### ISSUE TITLE
Need a Microsoft.Azure.Management.EventHub pkg for .net 4.5.

### ISSUE THREAD

**Issue by lifhu** [Azure/azure-event-hubs-dotnet#378]
## Actual Behavior
We have projects built against .net framework 4.5 and no Microsoft.Azure.Management.EventHub pkgs were able to built for it, except for 1.1.0, which is very old without management API we need.

## Expected Behavior
Need a Microsoft.Azure.Management.EventHub pkg for .net 4.5.

## Versions  
- OS platform and version:
- .NET Version: 4.5
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
Can you please report the request here: https://github.com/Azure/azure-sdk-for-net

**Comment by lifhu** [comment]
Created there, closing this one.
https://github.com/Azure/azure-sdk-for-net/issues/5307
