### ISSUE TITLE
Remove reference to deprecated WindowsAzure.Storage

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-event-hubs-dotnet#386]
It's been replaced
https://www.nuget.org/packages/WindowsAzure.Storage/

I'm guessing this should use
https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/

**Comment by serkantkaraca** [comment]
This is already merged into dev branch. https://github.com/Azure/azure-event-hubs-dotnet/pull/369

**Comment by AceHack** [comment]
Since this is closed does that mean it’s made it into a release?  If so what release?  If not how do I track it into a release?

**Comment by serkantkaraca** [comment]
This is not released yet. Planning to release 3.1 in the next 2 weeks.
