### ISSUE TITLE
Port exhaustion

### ISSUE THREAD

**Issue by yigitgursoy** [Azure/azure-event-hubs-dotnet#388]
We have an Azure API that pushes messages to multiple EventHubs instances.
When we load tested this API, we started seeing high outbound connections and port exhaustion errors.

Our implementation:

```csharp
var eventHubClient = EventHubClient.CreateFromConnectionString(eventHubConfiguration.ConnectionString);
await eventHubClient.SendAsync(eventData, partitionKey).ConfigureAwait(false);
await eventHubClient.CloseAsync().ConfigureAwait(false);
```

1) As MessagingFactory is removed from the library, what is best practice to reuse ports?
2) Is it safe to use static EventHubClient instances?

(EventHubClient doesn't have an Open() method or a method to get the status of the connection. This makes it almost impossible to write a custom connection pool mechanism.)

## Actual Behavior
1. TCP/IP Ports Exhausted error

## Expected Behavior
1. Reuse port / close port as expected

## Versions  
- OS platform and version: Windows 10 Version 1709 (OS Build 16299.1029)
- .NET Version: netcoreapp2.1
- NuGet package version or commit ID: Microsoft.Azure.EventHubs 3.0.0

**Comment by serkantkaraca** [comment]
You should not create dedicated eventhubclient for each message to send. As expected, that will waste an ephemeral port at each Send call which follows the Create. Try maintaining single client or a pool of clients depending on your traffic needs.

Yes, it is safe to use static client instances.

**Comment by yigitgursoy** [comment]
Thanks/teşekkürler Serkant.
