### ISSUE TITLE
Consider using .ConfigureAwait(false) throughout the code

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#39]
## Description

When awaiting for an async method, by default context is captured and attempted to be restored. Since this is a library, it could be used from UI or non-UI code. W/o specifying `.ConfigureAwait(false)` there will be some overhead of attempting to restore the context. To avoid that, awaited code should explicitly specifying not to restore the context.

> ConfigureAwait provides a means to avoid the default SynchronizationContext capturing behavior; passing false for the flowContext parameter prevents the SynchronizationContext from being used to resume execution after the await.
## Example

Before:

``` c#
await this.SendLinkManager.GetOrCreateAsync(timeoutHelper.RemainingTime());
```

After:

``` c#
await this.SendLinkManager.GetOrCreateAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
```

**Comment by serkantkaraca** [comment]
We have discussed the proposal in the team. The consensus is that the library doesn't need to be aware of its usage and actually it is apps responsibility to configure the awaits. We also have used the same practice in our .NET client as well.

**Comment by SeanFeldman** [comment]
@serkantkaraca I genuinely disagree with that statement.
Without `.ConfigureAwait(false)` context capturing is going to take place and [unnecessary code will be executed](https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Task.cs,2963) each time rather than being shorcutted. Is that truly a good idea? Thank you.

**Comment by SeanFeldman** [comment]
Extending a bit on the performance. Looking at the [`.ConfigureAwait()`](https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Task.cs,2963) code and execution path, when `false` is not passed in (ie default `true` is used), the code has to go through the logic within the [main if-block]( https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Task.cs,2974).  If `false` is used (ie explicit `.ConfigureAwait(false)` is used), execution is fast forwarded to a [single block execution]( https://referencesource.microsoft.com/#mscorlib/system/threading/Tasks/Task.cs,3014).

**Comment by SeanFeldman** [comment]
From Stephan Taub (TPL team) on this:

**Avoid Unnecessary Marshaling**

> As a library implementer, it’s a best practice to always use ConfigureAwait(false) on all of your awaits, unless you have a specific reason not to; this is good not only to help avoid these kinds of deadlock problems, but also for performance, as it avoids unnecessary marshaling costs. 

Source: https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/

**Comment by SeanFeldman** [comment]
MSDN magazine: https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by SeanFeldman** [comment]
[Roslyn suggestion](https://github.com/dotnet/roslyn/issues/7673) to allow library developers to configure `ConfigureAwait()` on the assembly level. This proposal enforces my point of a [library](https://github.com/vermorel) to use `ConfigureAwait(false)`.

If you want to take an easy route, there's a Fody Plugin called (what a surprise) [ConfigureAwait](https://github.com/distantcam/ConfigureAwait) which allows you to do exactly that. One drawback with it, it doesn't enforce the thought and easy to be omitted if forgotten.

**Comment by SeanFeldman** [comment]
[Jeffrey Richter](https://www.wintellectnow.com/Videos/Watch/performing-i-o-bound-asynchronous-operations?videoId=performing-i-o-bound-asynchronous-operations#) on capturing synchronization context and marshaling it back _and_ library methods video. Quoting (time 1:26:02)

> if you have a library method that has multiple `await`s in it, then you **must** apply `ConfigureAwait(false)` to every task that you await. You can't just do just a single one, you must have the **discipline** to apply it to every single one.

**Comment by SeanFeldman** [comment]
Excerpt from the book  [CLR via C#](https://www.amazon.ca/CLR-via-4th-Jeffrey-Richter/dp/0735667454)

> Developers creating class libraries definitely need to be aware of the `SynchronizationContext` class so they can write high-performance code that works with all application models. Because a lot of class library code is application model agnostic, we want to avoid the additional overhead involved in using a `SynchronizationContext` object. In addition, class library developers should do every-thing in their power to help application developers avoid deadlock situations. To solve both of these problems, both the `Task` and `Task<TResult>` classes offer a method called `ConfigureAwait` whose signature looks like this.

> As the preceding code shows, `ConfigureAwait(false)` must be applied to every Task object you await. This is because asynchronous operations may complete synchronously and, when this happens, the calling thread simply continues executing without returning to its caller; you never know which operation requires ignoring the `SynchronizationContext` object, so you have to tell all of them to ignore it. This also means that your class library code should be application model agnostic.

**Comment by danielmarbach** [comment]
@SeanFeldman is right. There is another problem. Since ConfigureAwait(false) only affects the continuations of an await the synchronization context of the thread entering the call stack will be restored. You are risking to reduce the performance of the caller by thousand of paper cuts. Every await statement which is called inside your library will contribute to that problem.

**Comment by serkantkaraca** [comment]
Thanks all providing invaluable resources on ConfigureAwait. As an example, I have review Storage API and apparently they are not practicing usage of ConfigureAwait. Please allow us sometime to settle down on this discussion. We are digging in some other resources and working with some other people. I will update you about what is going on. Thx again for the references you provided.

**Comment by SeanFeldman** [comment]
👍 @serkantkaraca 
Hopefully those will help 😃

**Comment by danielmarbach** [comment]
Happy to provide the PRs if you want. Just ping

**Comment by SeanFeldman** [comment]
@danielmarbach PR [like this](https://github.com/Azure/azure-event-hubs-dotnet/pull/41)? 😛

**Comment by danielmarbach** [comment]
@seanfeldman machine! :)

**Comment by serkantkaraca** [comment]
We are good to go Sean!!! Thanks for you time for providing all those nifty references. I will merge the change.

**Comment by SeanFeldman** [comment]
Thank you @serkantkaraca 
Going to open a 🍾 tonight to celebrate 😃

**Comment by danielmarbach** [comment]
Great news! 

![preview](https://cloud.githubusercontent.com/assets/174258/19919987/349f08f6-a0d6-11e6-8d6a-a36a7b81e437.jpg)
