### ISSUE TITLE
Exception "The requested name is valid, but no data of the requested type was found"

### ISSUE THREAD

**Issue by SebastianGau** [Azure/azure-event-hubs-dotnet#410]
## Actual Behavior
Background: I need to read data from an event hub in a VNET without public DNS resolution and access to event hubs via service endpoint only. To resolve the event hubs' IPs, I add the event hubs FQDN to the hosts file. I ensured that I can read and send events by directly using an event hub client, this definitely works. Access to the storage container (via https) is possible via proxy. 
1. When trying to read data from an event hub using EventProcessorHost, the following exception occurrs: "One or more errors occurred. (The requested name is valid, but no data of the requested type was found.)" This hints at some DNS issue, but i cannot isolate further whether this is related to event hub access or storage account access. I assume it is related to storage access.

## Expected Behavior
I assume are multiple ways to cope with his:
1. Make the EventProcessorHost independent of access to a storage account, e.g. by using an embedded database to achieve persistency of offsets, snapshots etc. Perhaps this can even be abstracted so that the user can freely choose his persistency layer. Is this possible?
2. Let the user specify that a proxy has to be used when accessing the storage via https. Of course this is not really my preferred option.

## Versions  
- OS platform and version: Windows Server 2019 Datacenter
- .NET Version: .net core 3.1
- NuGet package version or commit ID:

**Comment by serkantkaraca** [comment]
For item 1, track-2 SDK is already following that kind of principal. New client will support different checkpoint stores such as in-memory, file-system, storage etc.

Regarding item 2, Try passing storage client directly to the host. This way you can configure client's network properties.

Let me know if you hit any issues.

**Comment by serkantkaraca** [comment]
This repository has moved to https://github.com/Azure/azure-sdk-for-net

Please open the issue there if you are still seeing it.
