### ISSUE TITLE
BizTalk 2016 Event Hub Adapter (Send) - TimeOut

### ISSUE THREAD

**Issue by akishaha** [Azure/azure-event-hubs-dotnet#411]
## Actual Behavior
1. Getting TimeOut warnings with Biztalk Server 2016 EventHub Adapter

## Expected Behavior
1. No timeout as long as there are no resource throttling.

## Versions  
- OS platform and version: Windows Server 2016, BizTalk Server 2016
- .NET Version: 4.7

## Error
The adapter failed to transmit message going to send port "XXXXXXXXXXX" with URL "sb://XXXXX.servicebus.windows.net/XXXXX". It will be retransmitted after the retry interval specified for this Send Port. Details:"An unexpected failure occurred when processing a message. The text associated with the exception is "Details:The operation did not complete within the allocated time 00:01:00 for object message.(System.TimeoutException)". ".

**Comment by castillomartinezian** [comment]
Hi @akishaha . Have you find the root cause of this error and/or any solution?
All of the sudden this started happening to me as well recently.

Thank you.

**Comment by serkantkaraca** [comment]
This repository has moved to https://github.com/Azure/azure-sdk-for-net
Please open the issue there if you are still seeing it. You can also consider opening a Azure Support ticket so service side logs can be checked for failures.

**Comment by akishaha** [comment]
@serkantkaraca @castillomartinezian Issue is happening intermittently for us till now. Do we need to raise via Azure Support ticket only or do we have any other troubleshooting steps ?
