### ISSUE TITLE
Hard to Moq IEventProcessor's and derivatives

### ISSUE THREAD

**Issue by ghost** [Azure/azure-event-hubs-dotnet#415]
https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs.Processor/IEventProcessor.cs

It's currently very difficult to test EventProcessor implementations using Moq as the methods to be implemented by IEventProcessor interface take PartitionContext as a parameter, which is an object

Moqing an object is much more challenging than moqing an interface. It would be great if your team could change the params passed to be an interface (IPartitionContext) or something

**Comment by serkantkaraca** [comment]
This is the legacy SDK now and we won't be adding any new features or improvements. We will keep the SDK in maintenance mode such as bug fixes only. Please consider moving to https://www.nuget.org/packages/Azure.Messaging.EventHubs/

**Comment by serkantkaraca** [comment]
Closing since there is no further action needed.
