### ISSUE TITLE
Tests execution are done for a single target only

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-event-hubs-dotnet#48]
The client is targeting both .NET Standard 1.3 and .NET Framework 4.5.1, but tests are executed against .NET Starndard 1.3 only.

![image](https://cloud.githubusercontent.com/assets/1309622/19795476/fed1c3c6-9c98-11e6-883f-6c5fe2d1fa0a.png)

**Comment by serkantkaraca** [comment]
Good point Sean, test should run on both builds. I will try to find out how to configure this so we can run with more framework flavor.

**Comment by jtaubensee** [comment]
closing per PR #64
