### ISSUE TITLE
EventData.Properties is initially null for a new instance

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/azure-event-hubs-dotnet#78]
As the title says. :-) This is unintuitive for a developer who's accessing the property.

I want to do this:

    var eventData = new EventData(...);
    eventData.Properties["Foo"] = foo;
    eventData.Properties["Bar"] = myEvent.bar;

But I have to do this:

    var eventData = new EventData(...);
    eventData.Properties = new Dictionary<string, object>
    {
        ["Foo"] = foo,
        ["Bar"] = myEvent.bar
    };

**Comment by serkantkaraca** [comment]
Thanks for suggestion Lars. We will consider this.

**Comment by serkantkaraca** [comment]
This is addressed with https://github.com/Azure/azure-event-hubs-dotnet/commit/cad65f9e4e06f4ca31db7784b72b9535770622b8
