### ISSUE TITLE
I really want batch size calculation support

### ISSUE THREAD

**Issue by LarsKemmann** [Azure/azure-event-hubs-dotnet#79]
The `EventHubClient` should be able to handle batching of messages received via `IEnumerable<EventData>`, up to the total message size limit of 256 KB, automatically.

See [this comment on a related SO question](http://stackoverflow.com/questions/27263189/how-can-the-serialized-size-of-eventdata-be-determined-for-batching#comment62846484_27325426) for an explanation of why `SerializedSizeInBytes` is not sufficient for this problem.

**Comment by gambrose** [comment]
Automatically batching messages to work around the 256 KB limit would be good. But I would add that it would help if you also exposed the serialised size of the batch/events in the api.

In my scenario I am batching application messages inside event hub messages. Ideally each batched message would be 64 KB so as to get the most application messages per event hub message. Event hub message charges are not extortionate but if I can reduce them by a factor of 500 then It makes sense.
Having access to the serialised size of the batch, or what ever size is used in the billing, would allow me to dynamically adjust the batching sizes to get an optimum though put.
It would also allow me to report metrics so I can more accurately attribute event hub costs to different applications.

**Comment by serkantkaraca** [comment]
We are working on this feature request. It will be available in the next client release.

**Comment by serkantkaraca** [comment]
EventDataBatch feature checked in to dev branch.

**Comment by jtaubensee** [comment]
PR #157
