### ISSUE TITLE
EventData received timestamp

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-dotnet#91]
Request from @apulliam:

In wanting to test Event Hubs performance, it would be nice to have a current partition time stamp on the message when it is received, in order to calculate the duration that a message was on the Event Hub. In this scenario, Alan wants to test performance using Azure Functions, and due to the clock skew, some messages end up having negative duration.

So this proposal is to add a property to the `SystemPropertiesCollection` that would give a consistent time stamp.

**Comment by serkantkaraca** [comment]
Thanks John, let's follow up with this in the next meeting.

**Comment by jtaubensee** [comment]
Hi @apulliam - Would you be able to clarify your ask a little more? It seems straightforward at first glance, but when thinking about measuring end to end latency, providing an EventReceived timestamp would not be an accurate representation for what I suspect you are trying to measure. My point being, that the time when the message is stamped, is not necessarily the time when it is received (i.e. there is network latency to account for).
